### PR TITLE
[🧬 🧬  Release] v1.8.0-rc.0

### PR DESCRIPTION
**Pull request by W3stside**
## ⚠️ DO NOT SQUASH ⚠️ 
u_shall_not

--

# 🌵 Release v1.8.0-rc.0 🧬 

## Description
Adds the new Quote endpoint `v1/quote` for atomically calculating the price quote & fee. Checks a backend source for which best price strategy to use (`COWSWAP` (one quote request) or `LEGACY` (multiple price source request + competition)). 

## TODO:
- [ ] Query actual endpoint for price strategy - currently mocked using a false async function
- [ ] Review https://gnosisinc.slack.com/archives/CPZA1AGKY/p1639652242155600 
image

### CODE REVIEW

**Comment by alfetopito** [comment]
oh oh oh, please call this release "space odyssey"

**Comment by elena-zh** [comment]
Can't understand why, but at a moment I started to see a constant nose picking cow. See the video: https://watch.screencastify.com/v/hWQFS8eHaaN7yWa1Yt7c

The reason might be that Request URL: https://protocol-mainnet.dev.gnosisdev.com/api/v1/markets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48-0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/buy/100000000
 always gets 503 response..

**Comment by W3stside** [comment]
@elena-zh i believe that was a temporary problem, doesn't happen for me

**Comment by elena-zh** [comment]
@W3stside , great. I just reported it in order let you know about it and in order to double check whether it an important issue to fix or not, as I had not faced it before. 
But anyways, nice that it is not an issue.

**Pull request merged**
