### PR TITLE
Fixing Cypress

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixing integration tests by dodging the problem rather than fixing the root cause.
Don't actually know what's the root cause.
The error is somewhat related to EIP1193, ethersjs and vCOW test contract.

I solved this by instead not rendering anything that would do a network call to the vCOW contract

## Changes:
- Added new env flag `isCi` controlled by the env var `REACT_APP_CI`, used by the CI script when running Cypress
- Upgraded ethers and related packages to latest
- Moved Claim state updater to claim page, as this is the only place where we need to update it

### CODE REVIEW

**Comment by nenadV91** [comment]
Running `yarn integration-test` locally, the tests still fail. Can we ignore this?
Screenshot from 2022-02-01 18-47-42

**Comment by alfetopito** [comment]
> Running `yarn integration-test` locally, the tests still fail. Can we ignore this? Screenshot from 2022-02-01 18-47-42

Thanks for catching it.
Fixed.

**Comment by nenadV91** [comment]
Leandro I for me the tests are still failing locally
Screenshot from 2022-02-02 12-56-52

**Comment by alfetopito** [comment]
> Leandro I for me the tests are still failing locally Screenshot from 2022-02-02 12-56-52

@nenadV91 just resolved the conflicts and ran it again locally:

Screen Shot 2022-02-02 at 08 20 51

Have you ran `yarn` before to install the latest packages? Maybe that's what's missing :shrug:

**Comment by alfetopito** [comment]
Better fix on https://github.com/gnosis/cowswap/pull/2379

**Pull request closed without merging**
