### PR TITLE
Update Discord URL

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Updates the Discord URL 

/cc @avsavsavs

### CODE REVIEW

**Comment by avsavsavs** [comment]
Awesome!

**Comment by anxolin** [comment]
Can you give more context on this change?

**Comment by avsavsavs** [comment]
Brand Unification. 

instead of having invite/MHmz3knm2X as the URL, now when users click on the Discord, they will see that the URL invite is the same as twitter and that its cow related /invite/cowprotocol.

**Comment by elena-zh** [comment]
Hey @fairlighteth , @avsavsavs , It would be great to update this link as well then 
image

**Comment by elena-zh** [comment]
Btw, I think we should also update the discord link in the Cow.fi 
image
image

I have created an issue for this https://github.com/gnosis/cow-web/issues/68

**Comment by avsavsavs** [comment]
Totally agree @elena-zh!! Good catch

**Review by anxolin — APPROVED** [review]
Okok, it was strange change for me cause  we did this chat.cowswap.exchange domain for this, but i think adding the redirect is something not too many projects do, so probably better to show the discord link

**Comment by fairlighteth** [comment]
@anxolin Had the same thinking: Having a subdomain allows for a consistent and non-changing URL to communicate. But I think the other argument is favored in this particular case.

**Comment by avsavsavs** [comment]
yes, the problem is back then we did the chat.cowswap.exchange redirect, we could not yet do this new personalized invite. Also, the redirect works if you can read the link, if not you users just see the regular discord/invite/Mhtsks...

**Pull request merged**
