### PR TITLE
Hotfix 1.8.1 - Winter is gone (kind of)

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Removes the Christmas theme 
- there should be no snowfall effect
- reverts to old logo image and also to old submit order sound

Before -> After images
Screenshot from 2022-01-10 14-38-58
Screenshot from 2022-01-10 14-38-40

### CODE REVIEW

**Review by W3stside — APPROVED** [review]
Nice

**Review by biocom — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
LGTM!

**Comment by alfetopito** [comment]
@nenadV91 one question regarding this change.

Is it supposed to go out out with the rebranding deployment? Because that's already the version `1.8.1` in RC

It would just avoid merging it to `master` directly

I rather consolidate all of them in a single hotfix branch/PR to avoid overwriting changes by accident

There is at least one other change to be included which is https://github.com/gnosis/cowswap/pull/2071

**Comment by alfetopito** [comment]
> @nenadV91 one question regarding this change.
> 
> Is it supposed to go out out with the rebranding deployment? Because that's already the version `1.8.1` in RC
> 
> It would just avoid merging it to `master` directly
> 
> I rather consolidate all of them in a single hotfix branch/PR to avoid overwriting changes by accident
> 
> There is at least one other change to be included which is #2071

Mati's changes have been merged into this PR, so you are ready to go :)

**Pull request merged**
