### PR TITLE
Update DarkMode list styles.

### PR DESCRIPTION
**Pull request by biocom**
# Summary
- Addresses https://github.com/gnosis/cowswap/issues/1073
- Cleans up a transparent color, which I made obsolete by using the `transparentize` package.
- Minor style adjustment.

Screen Shot 2021-07-29 at 14 15 29Screen Shot 2021-07-29 at 14 15 09

  # To Test

1. Open the token selector.
2. Click on 'Manage token lists'
3. Paste a token list url from https://tokenlists.org/

### CODE REVIEW

**Review by elena-zh — COMMENTED** [review]
Great! Some minor issues: 
1. 'Loaded' checkmark is not displayed in the dark mode
checkmark
no checkmark

2. Token list is not displayed in the confirmation modal when add it
TOKEN LIST

**Comment by biocom** [comment]
@elena-zh Thank you for your review. Pushed fixes, please review when it's re-deployed.

**Comment by elena-zh** [comment]
@biocom , cool!
One thing is left, and it that has been broken by the latest changes: qty of tokens has become not visible in the dark mode. Could you please fix it?
Qty of tokens

**Comment by biocom** [comment]
Good find, pushed a fix now.

**Review by alfetopito — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Looks good now!
Tiny issue - period as separator is still missing between a token list name and qty of token. 
Anyways, looks good. Approved.
PERIOD
Screenshot_1

**Comment by biocom** [comment]
@elena-zh Ooh didn't see that one :) - Pushed a fix now.

**Comment by elena-zh** [comment]
@biocom , thank you! Verified!

**Pull request merged**
