### PR TITLE
Fix / handle stale V2 order data type in V3

### PR DESCRIPTION
**Pull request by W3stside**
# Summary
Fix old v2 order state breaking app

Fixes the whitescreen crash as reported by @fleupold seen here:
image

I input real data from @fleupold to test this. Logging when V2 order data detected:
image

## Testing
1. input into localstorage orders a bunk order in style of v2 WITHOUT `inputToken` or `outputToken` in the `order` object

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
Nice! solutions loos good to me. i trust you tested it correctly, but just to be sure can you include in the description the data to add to the local storage to easily reproduce for the reviewers?

**Comment by W3stside** [comment]
> Nice! solution loos good to me. i trust you tested it correctly, but just to be sure can you include in the description the data to add to the local storage to easily reproduce for the reviewers?

i did but it's huge.. didnt have the patience to detangle it but here:
https://pastebin.com/raw/8WfdsC8r

**Review by biocom — APPROVED** [review]
Was usually getting this error when switching chains, on a connected wallet. But looks good to me now!

**Review by alfetopito — COMMENTED** [review]
:+1:

**Pull request merged**
