### PR TITLE
Update FAQ: Does CowSwap have a token?

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Update FAQ for question: `Does CowSwap have a token?`

Old:
image

New (edited/updated):
image

### CODE REVIEW

**Comment by avsavsavs** [comment]
I would say, "...using a token, and that is why there is an ongoing discussion in the forum about the possibility of creating one"

**Review by elena-zh — APPROVED** [review]

**Comment by anxolin** [comment]
I changed the message slightly, let me know if it's better now!

**Review by avsavsavs — APPROVED** [review]

**Comment by MareenG** [comment]
The last part of the new section is missing. Is this intended? 
Bildschirmfoto 2021-08-03 um 16 27 02

**Comment by alfetopito** [comment]
> The last part of the new section is missing. Is this intended?
> Bildschirmfoto 2021-08-03 um 16 27 02

It was fixed, I can see the @MEVProtection paragraph

**Pull request merged**
