### PR TITLE
Default cursor for USD est./price impact.

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Addresses #1078 

https://user-images.githubusercontent.com/31534717/131343546-0cb1af27-d48e-40e5-970f-d718de54a261.mov

  # To Test

1. Pick a pair
2. Hover on the USD estimates / price impact
3. The default cursor should be shown.

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @biocom , great job!
However, some questions: 
1. Now we have different styles of cursor when hover on value: it would be nice to make it the same (`I` instead of the arrow is displayed on the rest amounts, and on the confirmation pop-up)
cursor
cursor1

2.  'Glove' is still displayed when hover a mouse on a balance in the 'To' field. 
You have mentioned [here ](https://github.com/gnosis/cowswap/issues/1078#issuecomment-888351444) that 'Max' button is useful: 100% agree. But there is no 'Max' button in the 'To' field, so could we remove 'glove' from there?
glove

**Comment by MareenG** [comment]
Looks good to me.
I also agree with Elena on point 1 and 2.

**Comment by biocom** [comment]
@elena-zh Addressed the points (wait for new build). One thing I noticed is that 0 balance is shown without the number. Not sure you experience the same:
Screen Shot 2021-09-06 at 12 33 44

**Review by elena-zh — APPROVED** [review]
@biocom , LGTM!

**Comment by biocom** [comment]
Merging with 2 approvals (1 dev). Please review post-merge in case you want to still address comments.

**Pull request merged**
