### PR TITLE
Fix for already claimed button on claim successful screen

### LINKED ISSUE #2416: 'Already claimed' button appears on the Claim successful screen
Do a successful claim (for yourself or on behalf)
Verify the Claim successful screen

**AR**: 'Already claimed' button appears on the Claim successful screen

**ER**: no 'Already claimed' button on the Claim successful screen

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #2416

Fixes the issue mentioned in the ticked
Couldn't test this properly because couldn't find working Rinkeby addresses.

### CODE REVIEW

**Comment by elena-zh** [comment]
The issue LGTM!
However, I have found another edge case: sometimes, when I try to cancel a transaction, I can face race conditions, so I can get a 'pending forever' transaction (reported in #1832)
So when Claim transaction runs into this state, I can see 'Already claimed' button on the Pending screen
Screenshot_9

However, I'm not sure whether we need to spend a lot of time in order to fix this..
@nenadV91 , @alfetopito , WDYT?

**Review by elena-zh — APPROVED** [review]
I have just retested: the issue I have described is reproducible in this PR

**Comment by elena-zh** [comment]
Btw, I was not able to reproduce the issue while testing #2485 PR.

**Review by alfetopito — APPROVED** [review]

**Comment by nenadV91** [comment]
@elena-zh I will merge this since I can't reproduce that, if it still happens we can will fix it in another PR.

**Pull request merged**
