### PR TITLE
adjusts for connect a wallet btn

### LINKED ISSUE #1817: [Profile] 'Connect to a wallet' button's text  is cropped in a mobile view
'Connect to a wallet' button's text is cropped in a mobile view

**Expected**: the button's text is not cropped

### PR DESCRIPTION
**Pull request by maria-vslvn**
# Summary

Fixes #1817  

imageimage

  # To Test

1. Be disconnected
2. Open the page `Profile`
2. reduce the screen width down to 320th px
3. see the connect a wallet btn text cropped

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
LGTM!

**Review by alongoni — APPROVED** [review]
Looks great Maria!

**Review by alfetopito — APPROVED** [review]

**Comment by anxolin** [comment]
Shold this PR be merged?

**Comment by alfetopito** [comment]
> Should this PR be merged?

Yes! We were discussing it today where it should be merged to.

We agreed to merge to release/1.5

**Comment by ramirotw** [comment]
should this PR be included in `release/1.5`? I changed the base branch and set the Auto-merge tag but the mergify bot has some issues with the cypress task not finishing

**Pull request merged**
