### PR TITLE
[Claim-Reject-Modals] Fixes empty modal

### LINKED ISSUE #2195: Empty modal is displayed when cancel approve transaction from the Set allowance form
Related to #2193 #2169

Empty modal is displayed when cancel approve transaction from the Set allowance form
Seems like it is duplicated:

### PR DESCRIPTION
**Pull request by W3stside**
Fixes empty modal as described by @elena-zh in #2195 
Closes #2195 

## Test
1. approve token
2. reject
3. (use acct with multiple investment options)

### CODE REVIEW

**Comment by elena-zh** [comment]
Seems that the build preview link can't appear due conflicts 😐

**Comment by W3stside** [comment]
> Seems that the build preview link can't appear due conflicts 😐

yeah sorry rebuilt it

**Comment by W3stside** [comment]
@gnosis/gp-qa @gnosis/gp-frontend gonna merge it, feel free to leave any comments after

**Comment by elena-zh** [comment]
LGTM!
Thanks!

**Pull request merged**
