### PR TITLE
[Technical Debt] top level console override (replacement for 2532)

### PR DESCRIPTION
**Pull request by W3stside**
Potential replacement of #2532 

Part of #1887 

## Testing
check PRaul for logs

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]

**Review by alfetopito — APPROVED** [review]
Definitely much cleaner.

Is there a way to override the behaviour if we ever want to, though?

Let's say there are cases where we still might want to log something. Shouldn't we still be able to?

**Comment by W3stside** [comment]
also I've added console.error as well to this. do we want this ux?

**Comment by alfetopito** [comment]
> > Definitely much cleaner.
> > Is there a way to override the behaviour if we ever want to, though?
> > Let's say there are cases where we still might want to log something. Shouldn't we still be able to?
> 
> ... that's a good point, let me do sth

You haven't pushed yet, have you?

Assuming not, I would suggest and optional `force` parameter that ignores the environment when set:

```ts
console.log('shit, this should be visible, ALWAYS!!', force=true)
// OR
console.force.log('same thing...')
```

The second option would be a proxy/wrapper that invokes regular logging fns.

WDYT?

**Comment by W3stside** [comment]
> > > Definitely much cleaner.
> > > Is there a way to override the behaviour if we ever want to, though?
> > > Let's say there are cases where we still might want to log something. Shouldn't we still be able to?
> > 
> > 
> > ... that's a good point, let me do sth
> 
> You haven't pushed yet, have you?
> 
> Assuming not, I would suggest and optional `force` parameter that ignores the environment when set:
> 
> ```ts
> console.log('shit, this should be visible, ALWAYS!!', force=true)
> // OR
> console.force.log('same thing...')
> ```
> 
> The second option would be a proxy/wrapper that invokes regular logging fns.
> 
> WDYT?

i like the second

**Comment by W3stside** [comment]
@alfetopito [713872c](https://github.com/gnosis/cowswap/pull/2537/commits/713872c681ee7aa80fa63075526d71663b920e26)

**Review by alfetopito — APPROVED** [review]
Noice!

**Pull request merged**
