### PR TITLE
Added some updates

### LINKED ISSUE #2579: Do not show vCOW card to a not connected user/user with 0 (v)COW balance
Do not show vCOW card to a not connected user/user with 0 (v)COW balance 
image

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #2579 and some other small improvements

- hides vCow card if there is no account or vCow balance
- while converting the vested amount stays
- change transaction message from converting to convert

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]
Looks good!
(just watch out for conflicts because I just merged something touching the same file)

**Review by anxolin — APPROVED** [review]
Looks great!


Just one comment, and not from this PR, so in case there's an issue, lets merge this one and do in another PR.

Is this correct? 
image

**Comment by nenadV91** [comment]
> Looks great!
> 
> Just one comment, and not from this PR, so in case there's an issue, lets merge this one and do in another PR.
> 
> Is this correct? image

Yep that is fine

**Review by elena-zh — APPROVED** [review]
@nenadV91 , works great now!
 I think, that the issue is not related to the current PR, but in iOS  'shimmer' effect has square boarders
image
We had the same issue reported for the menu and Claim buttons, and decided not to fix it (discussed here https://github.com/gnosis/cowswap/issues/2148#issuecomment-1028014495) 
So we can leave it as it is. Correct, @fairlighteth ?

**Pull request merged**
