### PR TITLE
Terms & Conditions update

### PR DESCRIPTION
**Pull request by biocom**
Updates the Terms & Conditions - solves for #915

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
2 tiny changes:

1. Make forum.gnosis.io a link
screenshot_2021-07-15_09-19-16

2. Insert white space OR new line on this section in the appendix. Not sure what's intended here
screenshot_2021-07-15_09-18-42

**Comment by biocom** [comment]
@alfetopito Thank you, fixed :)

**Comment by W3stside** [comment]
ah but wait i see now, the affiliate stuff isn't done right? @alfetopito @biocom so we should wait for that first no?

**Comment by biocom** [comment]
Don't see harm having terms without the features. Otherwise we should consult.

**Comment by alfetopito** [comment]
> ah but wait i see now, the affiliate stuff isn't done right? @alfetopito @biocom so we should wait for that first no?

I see the issue. @biocom you merged the latest from `develop`, right?
screenshot_2021-07-21_09-45-48

We shouldn't do that for 0.17. Would be better if you cherry-pick whatever you need from `develop` instead.

**Comment by alfetopito** [comment]
> We shouldn't do that for 0.17. Would be better if you cherry-pick whatever you need from `develop` instead.

Fixed it (force pushed removing `develop` merge)

**Review by alfetopito — APPROVED** [review]

**Review by W3stside — APPROVED** [review]

**Review by W3stside — APPROVED** [review]

**Pull request merged**
