### PR TITLE
Style game page + menu.

### PR DESCRIPTION
**Pull request by biocom**
- Styles the Cow game page and the menu item.
- Uses a simple css filter/blending to account for dark mode.

Note: To get the latest sprites/game version, please review https://github.com/gnosis/cow-runner-game/pull/1

https://user-images.githubusercontent.com/31534717/121221841-455fa100-c886-11eb-8407-8cea1cd9b13f.mov

https://user-images.githubusercontent.com/31534717/121221861-4bee1880-c886-11eb-8afc-6e26d15d6e32.mov

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
Approving, but I think we almost only need to change the the background

At least the sandwich and cow can have the original colors, I think they might look alright in darkmode. Isn't it?

**Comment by biocom** [comment]
> Approving, but I think we almost only need to change the the background
> 
> At least the sandwich and cow can have the original colors, I think they might look alright in darkmode. Isn't it?

Yes perhaps. Although specifically the 'black' colors lack a strong contrast against the dark blue background:
Screen Shot 2021-06-08 at 18 39 35

Using the background color from white mode, my impression was that it's a bit out of sync with the rest of the darkMode UI. What do you think?
Screen Shot 2021-06-08 at 18 42 15

Fine with using the light version of the game, in both light/darkmode. Obviously the one with colors is nicer to look at.

**Comment by alfetopito** [comment]
I prefer the white cow, background same as theme.

**Comment by biocom** [comment]
Updated now to reflect your comments. @alfetopito is this how you envisioned it? 

Screen Shot 2021-06-09 at 09 27 17
Screen Shot 2021-06-09 at 09 27 07

Btw the pixel glitches will not be there with the other cow game related PR.

**Review by W3stside — APPROVED** [review]

**Comment by anxolin** [comment]
You can update now to that last NPM package :)

**Comment by biocom** [comment]
@anxolin Thanks, updated with the latest package now.

**Comment by alfetopito** [comment]
> Updated now to reflect your comments. @alfetopito is this how you envisioned it?

YES!

**Review by alfetopito — APPROVED** [review]

**Comment by anxolin** [comment]
Awesome :)

**Pull request merged**
