### PR TITLE
[Paraswap] migration to v5

### LINKED ISSUE #1378: Migrate to Paraswap API v5
**Description**
Paraswap has a new version of their API:
https://gnosisinc.slack.com/archives/C0203Q9R4JJ/p1630500009015000

They have some nice docs on how to migrate:
https://paraswap-network.gitbook.io/api-v5-docs/api/v4-to-v5

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #1378

- migration from Paraswap v4 to v5

  # To Test

1. Go to Cowswap
2. Test different swap combinations to check if there is anything unusual in the prices related to the current production version or any other issues related to prices

# Note
- update solver address in the code

### CODE REVIEW

**Comment by biocom** [comment]
Did some brief testing and for those few tests, it seems to work great. Some points to note:
- I'm getting a bit lower Fees on this PR, which is great.
- On this swap the decimal seemed truncated on the fiat display for the input amount: 
- (LEFT is this PR <---> RIGHT is production)
Screen Shot 2021-09-20 at 10 35 18

**Review by alfetopito — APPROVED** [review]
LGTM

Only thing that I noticed is that sometimes theres a 533 response from paraswap
screenshot_2021-09-20_10-12-31

**Comment by alfetopito** [comment]
>On this swap the decimal seemed truncated on the fiat display for the input amount:

That's probably just rounding as I believe the same display logic is on prod and dev

**Comment by biocom** [comment]
> That's probably just rounding as I believe the same display logic is on prod and dev

Hmm I think the screenshots I shared aren't the right ones 🤔 . I was referring to seeing a truncated fiat value for the input field, looking something like '$342324.' 

I guess it looked weird to me seeing a number truncated ending with a dot/decimal. But can't reproduce for now...

**Comment by elena-zh** [comment]
>  was referring to seeing a truncated fiat value for the input field, looking something like '$342324.'

this might be reported in #1316

**Review by MareenG — APPROVED** [review]

**Comment by MareenG** [comment]
LGTM! 
This affects only mainnet right, as paraswap doesn't operate on xDai or Rinkeby?

**Comment by MareenG** [comment]
Only the issues reported before( #1426 #1427 ) are present in this PR

**Comment by alfetopito** [comment]
> > was referring to seeing a truncated fiat value for the input field, looking something like '$342324.'
> 
> this might be reported in #1316

Yes @elena-zh that's it.

@biocom I think the issue is that the formating fn reduces the precision for higher values. Need to work on that eventually.

**Review by W3stside — APPROVED** [review]
nice!

**Review by alfetopito — APPROVED** [review]
:+1:x2

**Comment by anxolin** [comment]
Are you guys getting sometimes: 
image

**Review by anxolin — APPROVED** [review]
Code looks great, works as expected. Only concern is their API failing some times...

**Comment by nenadV91** [comment]
Yes, it was mentioned before https://gnosisinc.slack.com/archives/C025G521XQD/p1632209701016600. Could be that our code sometimes produces more then one request to Paraswap almost instantly or in the time span of few seconds and they now limit some of those but I'm not sure about this.

**Pull request merged**
