### PR TITLE
Split refactor faq

### PR DESCRIPTION
**Pull request by anxolin**
# Summary
Part of #2541

Split FAQ and refactor. FAQ is out of control :) 
It's too big to read, and very unperformant. This PR breaks it  down into sections.

image

image

## Not included
🎨 Design not included. The PR is big enough. We can reiterate and make it nicer.

I discussed it with @fairlighteth , we can make iterarations:
1. Basic one, just to add nice sections with maybe icons as the home for the FAQ. Also improve the back button, and the ToC.
2. Try to show a side panel with the index of questions
3. Try to show another side panel with the list of sections

# Test
Check section to section, the content is equivalent to the original.
Please, don't include "style issues"  in this PR. Its out of scope. Already big enough

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @anxolin , great changes!
Some my notes: 
1. We have this section at the bottom of the FAQ list.
image

We may place it to the bottom of the main section. WDYT?
image


2. It would be nice to change the date in the general - 'What is MEV and how much MEV has been extracted from users to date?' section 
image

3. Protocol - Cancel an order --> 'this FAQ entry' does not navigate to anywhere. Should navigate to   Trading - 'How can I cancel an order' section
image

4. My notes for the 'Token' section are still valid: https://github.com/gnosis/cowswap/pull/2540#issuecomment-1072215487 and https://github.com/gnosis/cowswap/pull/2540#issuecomment-1072251017
5. Trading- How does a trader submit a valid order in CowSwap? --> 'pre-sign' does not navigate to anywhere. Should navigate to   'Protocol' - 'What is pre-sign?' section
image

Thanks!

**Comment by anxolin** [comment]
@elena-zh addressed most of the issues. 

For the vCOW address and listing COW, @avsavsavs might do the changes in another PR

**Comment by anxolin** [comment]
1. done
2. done
3. done
4. done
5. I added the (ugly) footer in all sections, right?
6. done

**Comment by elena-zh** [comment]
Hey @anxolin , seems that the last changes were not deployed due to the failed build

**Review by elena-zh — APPROVED** [review]
@anxolin , changes LGTM now. Thank you!

**Pull request merged**
