### PR TITLE
Improve dark mode color styles.

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Addresses #796 
- Updates the X close icon color on the tx popups.

https://user-images.githubusercontent.com/31534717/132230976-329654cd-66ce-4236-93d5-c093e1e3eefe.mov

https://user-images.githubusercontent.com/31534717/132236239-25d49f67-6a83-4339-900c-28551c3f9e7e.mov

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @biocom , great job!
Some minor issues from my side: 
1. In Android, when I start typing into the token search field, I get strike through 'Custom token' label. I assume it is due to keyboard raises up 'Tip' warning area. in iOS this area remains to be hidden when open the keyboard
 
image
image

2. The next case is more like an enhancement: can you separate custom token Tip area in the same manner as you separated 'Manage token list' area? 
image
image

Thanks

**Review by MareenG — APPROVED** [review]
LGTM. I didn't experience the styling issues mentioned by Elena.

**Comment by biocom** [comment]
@elena-zh Pushed some updates (wait for build)

https://user-images.githubusercontent.com/31534717/132345341-06dc4e1a-9729-4d2d-aa3f-45646293e363.mov

**Review by elena-zh — APPROVED** [review]
@biocom , great, thank you!

**Review by alfetopito — APPROVED** [review]

**Review by anxolin — APPROVED** [review]

**Pull request merged**
