### PR TITLE
Further styling of investment flow

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Investment flow styling (still WIP)
- Better color support between light/dark mode.

Screen Shot 2022-01-18 at 18 00 12

## Note
- Many todos pending
Screen Shot 2022-01-18 at 17 20 42

### CODE REVIEW

**Comment by alfetopito** [comment]
FYI, it's a bit broken on FF
Screen Shot 2022-01-18 at 10 24 36

**Comment by anxolin** [comment]
Same as leandro. Weird, cause it looked nice in your laptop

**Comment by elena-zh** [comment]
I have more or less nice views on FF on the Claim form, but I do not see changes from the screenshot above: 
 - I do not see airdrop option
 - Investment grids look like previous ones to me in this PR
image

**Comment by alfetopito** [comment]
> I have more or less nice views on FF on the Claim form, but I do not see changes from the screenshot above:
> 
>     * I do not see airdrop option
> 
>     * Investment grids look like previous ones to me in this PR
>       image

It's a different screen Elena.
The one we are talking about is the last one, after the approval screen

**Comment by elena-zh** [comment]
> > I have more or less nice views on FF on the Claim form, but I do not see changes from the screenshot above:
> > ```
> > * I do not see airdrop option
> > 
> > * Investment grids look like previous ones to me in this PR
> >   image
> > ```
> 
> It's a different screen Elena. The one we are talking about is the last one, after the approval screen

🤦

**Comment by elena-zh** [comment]
The same to me in Win10 +Chrome 
image

**Comment by elena-zh** [comment]
Hey @biocom , I'm still not 100% sure in this proposal, but maybe we could make this text left-aligned as all the rest elements on the page? 
image

**Comment by biocom** [comment]
@elena-zh Yes will address in future PR's.

**Comment by elena-zh** [comment]
Thanks! Then, changes under the current PR LGTM!

**Comment by elena-zh** [comment]
Just a tiny issue to address in the future PR is to adjust 1st step number to be displayed within the step area in FF: 
image

**Review by elena-zh — APPROVED** [review]

**Comment by W3stside** [comment]
Agree with comments: 
1. left align text 
2. Can we add padding to the orange highlight text at the top? The steps descriptor

**Comment by biocom** [comment]
@W3stside Yes, planned to address this separately to keep things going.

**Pull request merged**
