### PR TITLE
2602 - Fee update on user address change

### LINKED ISSUE #2602: Fees are not updated when change accounts
1. Connect to a wallet without a fee discount
2. Specify a pair of tokens to trade, an amount
3. Do not clear out the fields, change an account in MM to the one with a fee discount

**AR**: fee amount remains the same as for the account without a discount

Video:  https://watch.screencastify.com/v/h1NRlfWJoenNPFpwvQIZ

**ER**: fee amount should be updated

Actually, fee amount is changed when I reload the page/wait until the next fee update/change a token pair request

### PR DESCRIPTION
**Pull request by W3stside**
Fixes #2602 - fee was not being updated on user account changed

## Testing
Follow steps in #2602

### CODE REVIEW

**Comment by elena-zh** [comment]
Frankly, I do not know why, but the fee amount remains to be the same with a discount and without. See the video: https://watch.screencastify.com/v/ii7VO6Z0RY2W3nG9Ip50

**Comment by W3stside** [comment]
> * **🔭 [GP Swap](https://pr2605--gpswapui.review.gnosisdev.com)**: CoW Protocol v2 Swap UI

Don't think there's any subsidy applied to these environments (PR, barn)

**Comment by elena-zh** [comment]
> Frankly, I do not know why, but the fee amount remains to be the same with a discount and without. See the video: https://watch.screencastify.com/v/ii7VO6Z0RY2W3nG9Ip50

Anyways, I noticed that 'quotes' requests re-run on the account changing event.

**Comment by W3stside** [comment]
merging, please post merge review if necessary

**Pull request merged**
