### PR TITLE
Do not update txs other accounts

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Built on top of https://github.com/gnosis/cowswap/pull/1791

Txs updater now works only on current account, like orders

  # To Test

1. Do a wrap/approve tx
2. Change to a different account
3. Wait until the tx is mined (watch for wallets confirmation)
* There should not be a notification in the UI
* There should not be a tx in the activity history
4. Switch back to the first account
* After a few moments the pending tx should be marked as mined

5. Send another tx, but this time trigger a tx with a very low gas price, forcing it to be pending forever
6. Do a speed up in the wallet
7. Before it's mined, switch to another wallet
8. Repeat step 3 and 4
* Result should be the same

9. Repeat steps 5 to 9, but this time cancel the pending tx instead of speeding it up
* Result should be the same

  # Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alfetopito , great changes. 
I do not see toast notifications for transactions from different accounts now. Besides, transactions without speeding up them work fine. 
Cancelled transactions are removed from the activity list, but it is reported in #1382 
However, some issues: 
1. I was able to get 'pending forever' transactions when I speeded up Approve and Unwrap token transactions:
image

Transaction's hash is correct: it shows that transaction is successful. But the app does not change transaction's status when switch back to the account
https://watch.screencastify.com/v/HIRex3Q0vfQX1As18dwN

Unwrap: https://rinkeby.etherscan.io/tx/0xb6f9db65abd700efc7a278cd0b80a7ce3a65a6f8bd46faab31b21821f5559c99
Approve: https://rinkeby.etherscan.io/tx/0x169b22a7d823de541ece1a85e1319f115e76b11075696955c47f2da2580b765d

2. I was able to get 'Filled' speeded up 'Aprrove' transaction, however, the app navigates to an incorrect URL
app: https://rinkeby.etherscan.io/tx/0xed302db27b2bf755745eeee3a37a7701cc6f7af128c3d40f7ed915a849a836e8
correct hash: https://rinkeby.etherscan.io/tx/0xf5c111a475e77f1627d9a64024df4b6f0b39322cfc0820b5396137b53fcfcec9


This might be related to changes in #1532

**Comment by alfetopito** [comment]
>     1. I was able to get 'pending forever' transactions when I speeded up Approve and Unwrap token transactions:
>        image
> 
> 
> Transaction's hash is correct: it shows that transaction is successful. But the app does not change transaction's status when switch back to the account https://watch.screencastify.com/v/HIRex3Q0vfQX1As18dwN
> 
> Unwrap: https://rinkeby.etherscan.io/tx/0xb6f9db65abd700efc7a278cd0b80a7ce3a65a6f8bd46faab31b21821f5559c99 Approve: https://rinkeby.etherscan.io/tx/0x169b22a7d823de541ece1a85e1319f115e76b11075696955c47f2da2580b765d
> 
>     1. I was able to get 'Filled' speeded up 'Aprrove' transaction, however, the app navigates to an incorrect URL
>        app: https://rinkeby.etherscan.io/tx/0xed302db27b2bf755745eeee3a37a7701cc6f7af128c3d40f7ed915a849a836e8
>        correct hash: https://rinkeby.etherscan.io/tx/0xf5c111a475e77f1627d9a64024df4b6f0b39322cfc0820b5396137b53fcfcec9
> 
> 
> This might be related to changes in #1532

I could reproduce `2`, will take a look.
`1` is working fine for me, though. I've tested the speed-up of a unwrap tx.
Does it work when you refresh the page?

**Comment by elena-zh** [comment]
Yes, these pending transactions are still displayed for me. 
I closed this tab 1 or 2 hours ago, I have just reopened it and again see these pending transactions.
image

**Comment by alfetopito** [comment]
@elena-zh I've fixed `2`

Regarding `1`, could you share with me the contents of you local storage for key `redux_localstorage_simple_transactions`? In pastebin or something

Could not reproduce that yet. Maybe looking at your txs I can figure out what is causing it...

**Comment by elena-zh** [comment]
Hi @alfetopito , here are transactions from my local storage
https://pastebin.com/ppQMLQ7m

**Comment by elena-zh** [comment]
Regarding the case 2, changes LGTM!

**Comment by alfetopito** [comment]
> Hi @alfetopito , here are transactions from my local storage https://pastebin.com/ppQMLQ7m

Looking at the both pending txs you have:

```json
{
    "0x1b253d3e27448c557086222bcbea9f2c8fac734776e680d45f97976198ade6ff": {
      "hash": "0x1b253d3e27448c557086222bcbea9f2c8fac734776e680d45f97976198ade6ff",
      "transactionHash": "0xb6f9db65abd700efc7a278cd0b80a7ce3a65a6f8bd46faab31b21821f5559c99",
      "hashType": "ETHEREUM_TX",
      "addedTime": 1636387384168,
      "from": "0xFF714b8b0e2700303eC912BD40496C3997ceEa2b",
      "summary": "Unwrap 0.009 WETH to Ether"
    },
    "0x288fd6b5fd70ed50431b8490885904189d5d13fea4bee00e62c0698b6bbda07c": {
      "hash": "0x288fd6b5fd70ed50431b8490885904189d5d13fea4bee00e62c0698b6bbda07c",
      "transactionHash": "0x169b22a7d823de541ece1a85e1319f115e76b11075696955c47f2da2580b765d",
      "hashType": "ETHEREUM_TX",
      "addedTime": 1636387759329,
      "from": "0xFF714b8b0e2700303eC912BD40496C3997ceEa2b",
      "summary": "Approve WETH",
      "approval": {
        "tokenAddress": "0xc778417E063141139Fce010982780140Aa0cD5Ab",
        "spender": "0xC92E8bdf79f0507f65a392b0ab4667716BFE0110"
      }
    }
}
```

For the unwrap tx, the main tx hash (https://rinkeby.etherscan.io/tx/0x1b253d3e27448c557086222bcbea9f2c8fac734776e680d45f97976198ade6ff) doesn't exist, while the "secondary" (https://rinkeby.etherscan.io/tx/0xb6f9db65abd700efc7a278cd0b80a7ce3a65a6f8bd46faab31b21821f5559c99) is the one that got executed.

We only see both because of the bug I fixed on `2`.

But I can tell that the original tx hash was the one executed, while the one replacing it was the one that "lost" the race.

I assume this is a race condition:
1. You placed the tx `0xb6f9db65abd700efc7a278cd0b80a7ce3a65a6f8bd46faab31b21821f5559c99` with regular gas settings
Screenshot_20211109_145823
2. Right after you sped it up
3. The app picked up the speed up and updated the tx to `0x1b253d3e27448c557086222bcbea9f2c8fac734776e680d45f97976198ade6ff`
4. But, the first tx was executed

Similar thing with the Approve WETH tx.

---

For now, what you can do is clear the history and they will go away :)

Of course, not a long term solution, but seems unrelated to this change and should be addressed separately.
I think the solution is to keep track of all of the hashes until one of them is mined to avoid the race condition.

What do you think @anxolin @ramirotw ?

**Comment by ramirotw** [comment]
> For now, what you can do is clear the history and they will go away :)
> 
> Of course, not a long term solution, but seems unrelated to this change and should be addressed separately. I think the solution is to keep track of all of the hashes until one of them is mined to avoid the race condition.
> 
> What do you think @anxolin @ramirotw ?

Yes, that makes sense. We already have all that information to wait until either the old or the new tx are mined and then update the local state.

**Comment by anxolin** [comment]
> Of course, not a long term solution, but seems unrelated to this change and should be addressed separately.
I think the solution is to keep track of all of the hashes until one of them is mined to avoid the race condition.

Agree with this assessment. @ramirotw could you add this to your backlog, it's kind of an edge case, so not max prio, but nice to fix

**Review by anxolin — APPROVED** [review]

**Comment by anxolin** [comment]
@alfetopito I merged this one to consolidate.

**Pull request merged**
