### PR TITLE
[Release] - 0.17.0

### PR DESCRIPTION
**Pull request by W3stside**
### 🍆 YOU SHALL NOT SQUASH! 
u_shall_not
--
# 🌵🌵 Release 0.17.0
A great day for everyone!

🦖 🦕 🦖 🦕 🦖 🦕 🦖 🦕 

### 🏗️  Changes
1. Visual: Uniswap's V3 was merged to give us style/UX overhaul
2. USD Price Estimation: USD price estimation for most tokens. Calculated via our price logic against USDC.
3. Bug fixes:
    i. Unserialised Token data being saved via Orders to state > now serialised and cleaned up.
    ii. Unsupported networks and custom chains (xDAI) Ether class and errors: xDai now has a custom Ether class extended to properly use xDai as the native token. Fixes error whitescreening app for other unsupported chains (Ropsten, Kovan, etc)

### 📓 Changelog
74a3b721 disable lingui (#1023)
ff8ae7cd [Release 0.17] Reintroduce fee breakdown tooltips + change price display (#981)
40541b85 [0.17] Fix unsupported token error on fee (#1009)
d49bf848 fix fee colour and tooltip (#1008)
50adfd58 fix import in one remaining file to use GpEther (#1011)
f0cf37a0 Update styles add token to support darkMode (#1005)
8c3bd699 Update terms wallet modal. (#1002)
bae15710 Terms & Conditions update (#935)
46b76bbd [975] New to Ethereum? Blurb re-add (#1003)
930e13f3 word-break: break-all; (#1004)
22c09ad9 Turning wallect connect disconnect back on and adding Translation tags (#992)
c412973b [794] Dark mode fix token import bg colour (#976)
039cfb1b [877] Remove incompatible wallets (#971)
b996dc52 fix type change from merge
ea1f79db [617] USDC Price hook & price impact  (#900)
2bda3c06 [GP Ether] - Fixes broken Ether on XDAI and other non-supported networks (#918)
76cb3b2e isLocalAware: false (#940)
bb6e6912 exclude paraswap4 from query (#938)
c63ffc52 import path for constants/addresses
27ca5a45 extend addresses
b02b472d export addressmap
2e39506f Handling exceptions on getBestQuote (#907)
7d454a33 Non-Serialisable data sent to state (bug fix) (#909)
ac5f10c1 Update wrong word in COW FAQ (#908)
acd817ff 800 - Show consistent amounts via formatSmart (#895)
ec42581b Uniswap Protocol > CowSwap  Approve token wording (#897)
b3bf4505 [Cleanup] useRefetchPriceCallback spring cleaning (#879)
e543fea9 Translations: Remove all but en-US locales (#883)
ab61fe4a update yarn lock
e3553663 fix cancel order modal (#881)
b366fa83 [Uniswap V3 Merge] aka the worst thing ever (#810)
e90310b8 What is cowswap (#871)

### 👩‍🔬 Testing
1. VISUALS: lots of visual changes, please make sure colours are ok in both light and dark mode, and please check #681 for issues already catalogued
2. NUMBERS/AMOUNTS: the usual there.
3. COW GAME: that it works well in all formats: desktop, mobile (landscape, portrait), tablet
4. ORDER CANCELLATION: that it works in V3 context (same testing procedure as last release)
5. USD price estimations: please make sure:
  a. USDC USD price is always 1:1 e.g 500 USDC should show 500$
  b. the prices are not crazy divergent from other swaps (uni, sushi etc) - we pull prices differently than other swaps so some discrepancy is expected
6. XDAI - works as normal:
  a. token balances load (can open the token picker for easy checking)
  b. can trade normally, no errors happening
7. ROPSTEN/KOVAN/BLAH BLAH networks that we don't support should show: Wrong Network in the usual network place. No errors

--

### Remaining things (ordered by priority)
- [x] add back in (temporarily) fee breakdown modal until redesign implemented --> in progress #981 
- [x] xDai token balances not loading #925 --> #937 
- [x] Remove incompatible wallets #877 
- [x] Remove ParaswapPool4 from query #921 --> #938 
- [x] Dark mode fixes (e.g import token) #794 
- [x] formatSmart locale bug #905
- [x] re-add wallet modal connection message about accepting terms & conditions --> #935 & #915 & #916
- [x] update Terms and Conditions --> in progress #935 
- [x] add 'New to Ethereum? message to the connection modal #975

### CODE REVIEW

**Comment by alfetopito** [comment]
Something is up with the integration tests :/

**Comment by MareenG** [comment]
I am still testing but I think the current version should not go into production. 
The way the fees are displayed are quite off to the prior version. 
The main issue here that it is not 100% clear what the total amount is, from which value the fee is now deducted. 
Sell order
Bildschirmfoto 2021-07-15 um 15 16 37

buy order
Bildschirmfoto 2021-07-15 um 15 17 17

Beforehand it was nicely displayed how the amount were calculates. Now the UX is not as clear anymore. I would suggest to change the way we display the amounts before releasing to production.

**Comment by W3stside** [comment]
releasing rc.0 right now

**Comment by elena-zh** [comment]
Hi everyone!
Here in this PR, we have CoinBase, Fortmatis and Portis wallet connection options. These options are buggy ones: 
Fortmatis and Portis mention 'UniSwap' in conntion pop-ups ([video ](https://drive.google.com/file/d/1y4EqRvF1tS3_x5fRUM3WYb891xpuKjTq/view)), 
Coinbase is defined as Unknown wallet after connection
image

Should we report these issues and fix them in this release or we could disable these options for now (as it is currently done in the Staging environment)?

Thanks

**Comment by W3stside** [comment]
> Hi everyone!
> Here in this PR, we have CoinBase, Fortmatis and Portis wallet connection options. These options are buggy ones:
> Fortmatis and Portis mention 'UniSwap' in conntion pop-ups ([video ](https://drive.google.com/file/d/1y4EqRvF1tS3_x5fRUM3WYb891xpuKjTq/view)),
> Coinbase is defined as Unknown wallet after connection
> image
> 
> Should we report these issues and fix them in this release or we could disable these options for now (as it is currently done in the Staging environment)?
> 
> Thanks

I am currently in progress (done today eod) of disabling the buggy wallets.

**Comment by elena-zh** [comment]
Another question:  is this OK that 'WETH9' token is displayed by default in tokens lists instead of WETH?
image

**Comment by W3stside** [comment]
@elena-zh please check https://github.com/gnosis/cowswap/pull/971 (incompatible wallets)

**Comment by W3stside** [comment]
> Another question: is this OK that 'WETH9' token is displayed by default in tokens lists instead of WETH?
> image

It is inline with how Uniswap represents WETH9, so yes. 

Though if you believe this is something we should discuss changing and/or users have complained about, I'm happy to have an issue opened for changing this

**Comment by MareenG** [comment]
On mobile quite a few things are broken #1016  
It might be related to some translation/language settings inherit from Uniswap

**Pull request merged**
