### PR TITLE
Do not allow to wrap for unsupported wallets

### LINKED ISSUE #1845: 'Wrap my XDAI/ETH' section is enabled when a wallet is not supported
Reproducible on Prod

1. Connect to a wallet that is not supported
2. Select XDAI/ETH in the From section
3. Select a token to buy
4. press on the Wrap my  XDAI/ETH button

**AR**: transaction is running, a request to sign the transaction is sent to the connected unsupported wallet

**ER**: the button is disabled, 'Wallet Unsupported' is displayed on it

### PR DESCRIPTION
**Pull request by anxolin**
# Summary
Closes #1845
Do not allow to wrap ETH or xDAI for unsupported wallets.

# To Test

* Connect to a wallet that is not supported
* Select XDAI/ETH in the From section
* Select a token to buy
* Observe that the wrapping message is not visible any more

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @anxolin , could you please disable an access to Gnosis safe in XDAI for this PR in order to test these changes?

**Review by alfetopito — APPROVED** [review]
Tested with Crypto.com defi-wallet

Not able to Wrap.

Although, I remember there was a link to FAQ at the bottom, no?
screenshot_2021-11-16_11-04-17

**Review by elena-zh — APPROVED** [review]
Retested changes with WalEth and 1inch wallets: the section does not appear when ETH is selected in the Sell token field. 

@alfetopito , no, there was no FAQ section at the bottom for 'Wallet Unsupported' case. Only for  'Unsupported token' case

**Comment by anxolin** [comment]
> Although, I remember there was a link to FAQ at the bottom, no?

@alfetopito u are right, although not anymore in PRODUCTION, so is not part of this PR:
image

**Comment by anxolin** [comment]
@alfetopito I created https://github.com/gnosis/cowswap/issues/1874

**Comment by anxolin** [comment]
> Elena, these are the wallets (besides Safe on xDai that are unsupported)

Sorry @elena-zh i should have given better instructions.

**Comment by elena-zh** [comment]
@anxolin , it is all right! In the end I was able to test it 🧐

**Pull request merged**
