### PR TITLE
Add link to the profile

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Adds link to the profile. 
* ⚠️ This link won't be visible when you claim on behalf of someone else. This is because, this someone else is the one that received the tokens, not the connected account. The profile shows the balance only for the connected wallet.

image

## Not included
I didn't include any style. I assume @biocom will revisit this screen completely. Michel, let us know if you want help mocking the app to get to this screen without the need to claim tokens each time.

# To Test

1. Claim for your self. You might need to use some of the PK in https://docs.google.com/spreadsheets/d/1pf97wtawkibZPNTrVbyo2FSZKXf6Xo_A0sddWXKxnE4/edit#gid=390159133
2. Verify the link is visible

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @anxolin , great changes!

Just small improvements I'd like to suggest: 
1. It would be nice to navigate a user to the top of the Profile page when press on the 'Profile' link
Video: https://watch.screencastify.com/v/NokA3oJZ9G2ctQtooi6r

2. It would be nice to add a message that tokens were claimed for the account <   account  > . WDYT?
image

**Review by W3stside — APPROVED** [review]
styles are a bit strange but that's not for this PR, approved

**Review by alfetopito — APPROVED** [review]
Approved and I second Elena's suggestion of showing which account this was claimed to, to be explicit

**Comment by anxolin** [comment]
> 1. It would be nice to navigate a user to the top of the Profile page when press on the 'Profile' link

Agree, however, i think this is true for every navigation. So, i assume we should have a middleware or something. I will add this in our list of good to haves.

> 2. It would be nice to add a message that tokens were claimed for the account < account > . WDYT?

Sounds good. I will just add something basic. I think Michel will just move things around, so I'll try to not over do it.

**Comment by anxolin** [comment]
For 2. 
image


Yes, it needs styles :)

**Pull request merged**
