### PR TITLE
Re-enable TokenPocket wallet via WalletConnect

### LINKED ISSUE #673: [WalletConnect] Enable TokenPocket
TokenPocket wallet has been disabled temporarily until signing is implemented for WalletConnect.

TP team is working adding it https://github.com/TP-Lab/tp-android/issues/16

### PR DESCRIPTION
**Pull request by alfetopito**
# Update 2021/06/15

TokenPocket has released their update and it's now working flawlessly :)

# Summary

Closes #673 

## Note

I'm opening this PR to allow TP team to test their fix(https://github.com/TP-Lab/tp-android/issues/16), since the wallet was disabled via WalletConnect on https://github.com/gnosis/gp-swap-ui/pull/597

# Testing

Using the PR's url:
1. Connect via WalletConnect using TokenPocket wallet
- [ ] The wallet should not be disabled

### CODE REVIEW

**Comment by biocom** [comment]
Just tested, and it seems like it works connecting? Although not WalletConnect but recognises as a Metamask:

**Review by biocom — APPROVED** [review]

**Comment by alfetopito** [comment]
> Just tested, and it seems like it works connecting? Although not WalletConnect but recognizes as a Metamask:

Yes, the in app browser was working before and was not disabled.
This change re-enables the connection over WalletConnect.
So, you didn't test what needs testing =P

**Comment by biocom** [comment]
> > Just tested, and it seems like it works connecting? Although not WalletConnect but recognizes as a Metamask:
> 
> Yes, the in app browser was working before and was not disabled.
> This change re-enables the connection over WalletConnect.
> So, you didn't test what needs testing =P

So basically, that means I'm a bad tester and bad reader? 😝 Will re-test.

**Review by anxolin — COMMENTED** [review]
I'm afraid is not ready in IOS

https://github.com/TP-Lab/tp-ios/issues/2

image

**Comment by biocom** [comment]
Yes works now:
Screen Shot 2021-06-16 at 15 45 32

**Review by anxolin — APPROVED** [review]
Works with the latest IOS version! 
image

**Pull request merged**
