### PR TITLE
[Bugfix] Move About item from Header to ellipsis menu

### LINKED ISSUE #995: SWAP action button overlaps the app logo in a mobile view
Related to #951

Swap action button has started to overlap app's logo after the Profile button was added to the header

**Expected**: buttons should not overlap logo
Add Menu?

### PR DESCRIPTION
**Pull request by matextrem**
# Summary

Fixes #995 

*As part of the issue tagged above, `About` item was moved from Header component to the ellipsis menu*

image

image

  # To Test

1. Open `swap` or `profile`
- [x] Verify the header component does not contains the `about` page
2. Click on the ellipsis in the top right corner
- [x] Verify the menu contains `About` page
- [x] Check if clicking on this item goes to `about` page

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
I have one concern here on removing the `about` from the header.

I believe the most up to date information regarding the Profile page is that it'll not be displayed at all for accounts not logged in.

@biocom would you be ok having a single entry in the menu (swap) in that case?

I'm not sure what would be the best behaviour.

**Comment by biocom** [comment]
@alfetopito Good point. Couple of options:

A. Hide "Profile" when not logged in
B. Show "Profile" at all times
C. Show "About" **when not connected** with a wallet -> Show Profile **when connected**.

I'd favor consistency and it's nice to have the user anticipate on features. What I mean:

1. Show the Profile link at all times (B) -> Users will be trained from start about this page/feature.
2. If you access the Profile page without being connected, we can still show the metric modules (volume, etc.), but ask the user to connect their wallet.

This way users can both explore/learn about (anticipated) features while being incentived to connect their wallet and interact.

Let me know your thoughts.

**Comment by alfetopito** [comment]
> @alfetopito Good point. Couple of options:
> 
> A. Hide "Profile" when not logged in
> B. Show "Profile" at all times
> C. Show "About" **when not connected** with a wallet -> Show Profile **when connected**.
> 
> I'd favor consistency and it's nice to have the user anticipate on features. What I mean:
> 
>     1. Show the Profile link at all times (B) -> Users will be trained from start about this page/feature.
> 
>     2. If you access the Profile page without being connected, we can still show the metric modules (volume, etc.), but ask the user to connect their wallet.
> 
> 
> This way users can both explore/learn about (anticipated) features while being incentived to connect their wallet and interact.
> 
> Let me know your thoughts.

I'm fine with that approach.

@annamsgeorge would you be ok with this behaviour? (always showing the profile page)

**Comment by matextrem** [comment]
@alfetopito @biocom any updates on this ? Should we continue with the approach mentioned above ?

**Comment by alfetopito** [comment]
> @alfetopito @biocom any updates on this ? Should we continue with the approach mentioned above ?

@matextrem I'm double checking with the team internally.

The feeling so far is that we are good to go with the profile page always visible.

We have a pending decision on what to show when the user is not connected, but that should be handled in a different task/PR.

**Review by alfetopito — APPROVED** [review]

**Comment by alfetopito** [comment]
I forgot to update this.
Got a confirmation that we are ok always showing the profile page.

@matextrem you are good to go with this change

**Pull request merged**
