### PR TITLE
Use the right modal for all operations

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

This PR completes the confirmation modals workflow. Before we had hardcoded the "type of operation", so we were showing a message mentioning something about signing an order even for the approve, wrap, unwrap and cancel operations.

Now it shows:

## Unwrapping
Screenshot at Oct 26 17-30-19

## Wrapping
Screenshot at Oct 26 17-30-57

## Swapping
Screenshot at Oct 26 17-31-29

## Approving
Screenshot at Oct 26 17-33-03

## Soft cancelling
For this one, I also changed a bit the message so it doesn't feel so broken. However, future PRs could improve and customize further any of these messages.

Old message:
Screenshot at Oct 26 17-34-05

New message:
image

# To Test

Just try out all the operations above :)

### CODE REVIEW

**Review by fairlighteth — APPROVED** [review]
Looks good, approved with one point of attention (Unwrap Ether text).

**Review by alfetopito — APPROVED** [review]
Ahh, much better!

**Review by fairlighteth — APPROVED** [review]
Looks good to me. I would probably ditch the '..for trading' text in the title, when doing an approval.

**Review by elena-zh — APPROVED** [review]
Changes LGTM!

As for 

> I think that's an independent issue. We are not sowing the min-amount. You are right we should, but out of the scope of this PR.

I'd say that this might be a part of #1155  that has not been fixed yet. 

Thanks!

**Pull request merged**
