### PR TITLE
Pr2232/follow up

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Follow up to #2232 

Screen Shot 2022-01-20 at 09 59 04

* Fixed remaining percentage
* Refactored a bit how percentage is calculated
* Added xDai logo

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
Great cleanups.

I don't think is from this PR, but I think we should always use this formatter with thousands separators. In your screenshot we can see it without

**Comment by alfetopito** [comment]
> Great cleanups.
> 
> I don't think is from this PR, but I think we should always use this formatter with thousands separators. In your screenshot we can see it without

Yes, I'll get there :)

**Comment by biocom** [comment]
Small suggestion after seeing the last screenshot:
- When 100% of investing available is **not** utilized, we could instead say: 
> Note: You will **not be able** to invest anymore after claiming.

**Comment by alfetopito** [comment]
> Small suggestion after seeing the last screenshot:
> 
>     * When 100% of investing available is **not** utilized, we could instead say:
> 
> 
> > Note: You will **not be able** to invest anymore after claiming.

@biocom  Like this?
Screen Shot 2022-01-20 at 11 55 19

**Comment by alfetopito** [comment]
I've applied the change as suggested. If we want to get back the remaining % just revert the commit https://github.com/gnosis/cowswap/pull/2236/commits/10b8a86b2d01ea17f2a11af6608239d4360fe7de

**Comment by biocom** [comment]
@alfetopito I actually meant to have a conditional note:
- 0% / nothing invested -> Note: You will not be able to invest anymore after claiming.
- Partial investment -> Use our previous solution with the 'can't invest the XX% remainder..."

But at the end, I like this general note as well, as it covers both scenarios.

**Pull request merged**
