### PR TITLE
Change text

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Change texts for the 1st step in the investment flow as suggested by Anna and Mindy

image

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @anxolin , seems like the ending period is missing here:
image

Also, is this OK that we are navigated to the Cow.fi from both these links? 
image

**Comment by nenadV91** [comment]
+1 to what Elena mentioned

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Still needs a period in the end of the sentence
image

**Comment by anxolin** [comment]
> Also, is this OK that we are navigated to the Cow.fi from both these links?

yes for now we don't have the final links

**Comment by W3stside** [comment]
Approved

**Pull request merged**
