### PR TITLE
Add vesting banner.

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Decided to replace the black color of the banner (in light mode) with a more dark blue color.
- Added a vesting explainer banner
Screen Shot 2022-01-27 at 12 37 43
Screen Shot 2022-01-27 at 12 37 52
Screen Shot 2022-01-27 at 12 39 02

vCow banner in previous step (from `vcow-banner`)

Screen Shot 2022-01-27 at 12 39 16

## Note
- Feel free to suggest another text. The idea is to keep the text in the banner short and descriptive.

### CODE REVIEW

**Comment by elena-zh** [comment]
@biocom , cool!
Some notes: 
1. the link remains underlined when click on it
image

2. Maybe we could also add this banner to the last investment screen to remind a user what is vesting once again? Frankly, I'm not sire about it, but proposing 😏

**Comment by biocom** [comment]
@elena-zh Thanks for reviewing.

1) Hmm, thought I had disabled all those. Will review again.
2) I thought about it too. My initial thinking was, we show it once, giving the user a one-time opportunity. Repeating feels like a lot of repeating. But I'm open to the idea and will play with it now.

**Comment by biocom** [comment]
@elena-zh pushed a fix for 1) 

It was the :focus instead of :visited (which I already had covered). Should be fine now.

As for showing the banner on the other screens: My recommendation right now is to **not** show it there. Main reason is that those pages are quite information dense and adding more content (e.g. the banner) will be a lot. 

The 'start' page (step 1) is meant as an explainer page, where the users always could go back to.

In case anyone else feels strong about this, let me know.

**Review by elena-zh — APPROVED** [review]
@biocom , agree. 
Approved!

**Pull request merged**
