### PR TITLE
FAQ - Styles on Links 

### LINKED ISSUE #1828: [FAQ - affiliate]: some links are not underlined
1. Open FAQ
2. Scroll down to the 'Why do I see more trades and referrals in my profile page than I actually see in the activity list?' question

**AR**: 2 links are not underlined

**ER**: all links should be underlined

### PR DESCRIPTION
**Pull request by alongoni**
# Summary
Closes #1828 

image
  # To Test

1. <<Step one>> Open the page `FAQ` and check the external links look and feel.

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alongoni , great. Now I can see an icon near the link in the FAQ section. 
However, now FAQ section has different links' styling in comparison with links on other pages: 
 - Terms
image

 - About
image

 - token links
image
image

 - token lists' links (menu and links itself)
image

So we need to decide whether change links' style everywhere in the app. Or leave them as it is, including FAQ section.

**Comment by alongoni** [comment]
Thanks @elena-zh, you are right. 
Maybe we can remove the icon I added in this PR and discuss it later to improve external links in all the app.
Are you agree? @alfetopito

**Comment by alfetopito** [comment]
Agree, do think we need this icon just yet

**Review by elena-zh — APPROVED** [review]
LGTM!

**Review by anxolin — APPROVED** [review]

**Pull request merged**
