### PR TITLE
Improve claim someone

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Improve a bit the link to the account you claim on behalf of

* Shorten link (as suggested by @alfetopito )
* Kill the brackets (as suggested by @elena-zh and @alfetopito )
* Add copy button as suggested, well add copy button cause when we shorten we are supposed to do that!

Before:
image

After:
image

# To Test

1. Claim of behalf of someone
2. Test the link, copy the address

### CODE REVIEW

**Comment by biocom** [comment]
Love the improvements, makes it look way better. Some small nits:
- On mobile the address is not centered, this is due to the parent button element having a `min-width` setting:
Screen Shot 2022-01-26 at 21 47 59
Screen Shot 2022-01-26 at 21 49 42

I can address these separately in case you want to leave it here.

**Comment by W3stside** [comment]
can you clean the history please?

**Comment by alfetopito** [comment]
Also, shouldn't this be pointing to the release branch instead?

**Comment by anxolin** [comment]
> can you clean the history please?

> Also, shouldn't this be pointing to the release branch instead?

All the same thing. It was pointing to `develop` instead of the `release/1.10`

**Comment by anxolin** [comment]
> On mobile the address is not centered, this is due to the parent button element having a min-width setting:

> I can address these separately in case you want to leave it here.

Yes, the min-width was used just to reserve some space for the message you see when you click. 
I removed it for responsive.

**Comment by elena-zh** [comment]
Changes LGTM besides the issue @biocom has mentioned [above](https://github.com/gnosis/cowswap/pull/2319#issuecomment-1022591189)

Nitpick that is not related to the current PR, but anyways: I'd not separate an amount from the vCOW token name when moving to another line
image

**Comment by anxolin** [comment]
Merging, let me know if you want me to address any other issues

**Pull request merged**
