### PR TITLE
[Claim] Rejected/failed/errors in claim flow

### PR DESCRIPTION
**Pull request by W3stside**
# Summary

#### Screenshots
_Approving_
Screenshot 2022-01-17 at 11 14 20

_Airdrop Claim (first page)_
image

## To Test
AIRDROP
1. using an account with airdrop and investments: 0xB1B98E968E9D7c6Ee1aa3496A753ae8922FC4683
2. first only leave airdrop selected (the preselected one)
3. hit claim
4. reject wallet tx
5. check error is as my screenshot shows
INVESTMENT
1. using an account with airdrop and investments: 0xB1B98E968E9D7c6Ee1aa3496A753ae8922FC4683
2. select the investment option (unselected one)
3. go thru the screens until on the investment approve screen
4. since this acct already has approves, click the "invest max" button (it is test coded to reject)
5. check error is as my screenshot shows for investment

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @W3stside , errors work nicely, however, I'd make them to be displayed a bit better in terms of UI. Maybe @biocom could help with this in a separate PR. 
Besides, I'd like to propose to show a error message when something goes wrong with the TX and it fails. WDYT? 
image
Anyways, it is not an issue for this PR, so let me know if I need to create a separate issue for this. 

I have to notice, that mentioned above error handling works somehow for airdrop, so it would be nice to adjust this error:
image

But still I can receive a 'Success' message when Claim fails (reported in #2082)
image

**Comment by W3stside** [comment]
> Hey @W3stside , errors work nicely, however, I'd make them to be displayed a bit better in terms of UI. Maybe @biocom could help with this in a separate PR. Besides, I'd like to propose to show a error message when something goes wrong with the TX and it fails. WDYT? image Anyways, it is not an issue for this PR, so let me know if I need to create a separate issue for this.

so instead of the message below showing it failed, showing a popup? 

> I have to notice, that mentioned above error handling works somehow for airdrop, so it would be nice to adjust this error: image

same question as above

> But still I can receive a 'Success' message when Claim fails (reported in #2082) image

let's make this it's own issue, not really for this PR

**Review by anxolin — COMMENTED** [review]
Can we make it coherent with the swap? there we show 
image

**Comment by elena-zh** [comment]
The message has become shifted after the latest fix 
image

image

**Comment by W3stside** [comment]
@elena-zh @anxolin this PR is the base now for #2193 - the UX will be Error modals now like the swap page (what anxo screenshotted) and no longer those error messages. Please check #2193 first

**Pull request merged**
