### PR TITLE
Swap page layout

### LINKED ISSUE #1276: Scroll on the Swap page when screen resolution is 1536 x 864 and less
When I open swap page  in the desktop version when screen resolution is 1536 x 864 and less, I see a scroll bar. However, there is a plenty room on the page. 
Sometimes, scroll disappears when I close  a banner notification (this is in Chrome and Brave): 
https://drive.google.com/file/d/1RPxrer7jSZ2atTnM4Zp3OuySJM27SVeb/view

Sometimes closing notification bar does not help 
https://drive.google.com/file/d/1Prxfwere0IhlrhNmRHImdNl3eelqOAAI/view

**Expected**: do not show scrollbar in the Swap page in a default state

### PR DESCRIPTION
**Pull request by alongoni**
# Summary
Fixes #1276 and #1550

The layout has changed a bit. Some small resolutions now have less padding on top but the scroll not appear. 
Before (on production with scroll):
image
image

After (on this PR without scroll):
image
image

  # To Test

1. <<Step one>> Open the page [`Swap`](https://pr2488--gpswapui.review.gnosisdev.com/)

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
LGTM!

**Comment by biocom** [comment]
Thanks for checking this. My comments:

1. I'd add a bit more margin between header and the container.
2. Please double check all the other (content) pages if this still looks right (incl. mobile).

**Review by alfetopito — APPROVED** [review]
Looks good to me, just make sure Michel's comments are accounted for and I think it's good to go

**Comment by alongoni** [comment]
Please @elena-zh can you test it again? Thanks!
cc @michelbio

**Comment by elena-zh** [comment]
Changes LGTM. 
The only difference I see in UI in comparison with Prod, is that there is a smaller margin between footer elements and the end of the content page in a tablet/mobile views
footer elements

But again, we have #1550 issue on the board that is related to footer elements displaying, so the issue might be fixed there. 

@alfetopito , @biocom , WDYT?

**Comment by alongoni** [comment]
hey @elena-zh Thanks. I can tackle #1550 issue in this PR.

**Comment by elena-zh** [comment]
@alongoni , looks much-much better. 
The only issue I could mention is that the footer is displayed in a 'hovered' state when a screen resolution is less than 720 px. See the video: https://watch.screencastify.com/v/n5Gmhpbn6a4cS4X4tUgA

Can we fix it somehow?

**Comment by alongoni** [comment]
> @alongoni , looks much-much better. The only issue I could mention is that the footer is displayed in a 'hovered' state when a screen resolution is less than 720 px. See the video: https://watch.screencastify.com/v/n5Gmhpbn6a4cS4X4tUgA
> 
> Can we fix it somehow?

Yes, I saw it. But I think this behavior is ok since in mobile we don't have a :hover state. So in mobile the text has by default the max contrast between the text color and the background. Maybe we can leave it as it is.

**Review by elena-zh — APPROVED** [review]
Approved then!

**Pull request merged**
