### PR TITLE
Re-enable Gnsosis Safe for xDAI

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Re-enables Gnosis Safe in xDAI

# To Test
* Connect to Gnosis safe in xDA
* Try to wrap, approve, trade

### CODE REVIEW

**Review by W3stside — APPROVED** [review]
Nice

**Review by alfetopito — APPROVED** [review]
Tested with a 1:1 xDai Safe, working fine!

Minor thing which is not related to changes in this PR but just to let you know, the approval tx is still pending
Screenshot from 2021-12-16 12-09-10

**Comment by elena-zh** [comment]
@anxolin 
Changes LGTM besides 2 issues: 
1. transaction response takes too long #2005 (reported as a separate issue)
2. Need to rewrite validation message when we try to buy xDAI (would be nice to fix in this PR)
image

**Comment by anxolin** [comment]
Thanks for the tests! merging and deploying

**Pull request merged**
