### PR TITLE
Fix xdai logos

### LINKED ISSUE #1102: [0.17] Broken WXDAI icon in From/To fields
Related to #1099

The token icon looks like a broken one all the time in From/To fields however, it looks good in the token list

**Expected**: WXDAI icon is not broken

Note: issue with the rest broken icons for xDAI is reported in #1103

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Close #1102 

Allow to provide override for images for some tokens. 

Creates a new mod for `CurrencyLogo`. The only change, is that if there's a known override, it's used instead of trying to get the token image from the address.

Now xDAI has logos :) 

image

### CODE REVIEW

**Comment by biocom** [comment]
No PR deploy link?

**Review by elena-zh — APPROVED** [review]
LGTM!

**Comment by anxolin** [comment]
This PR had an issue with a ciclic dependency. Is solved now. @alfetopito u can review after merging

**Review by alfetopito — COMMENTED** [review]
:+1: 

Only one question from yesterday :)

**Pull request merged**
