### PR TITLE
[877] Remove incompatible wallets

### LINKED ISSUE #877: [V3] Remove un-usable Wallets
Remove the unusable wallets from the wallet picker

### PR DESCRIPTION
**Pull request by W3stside**
Closes #877 

### Removes the incompatible/buggy wallets

image

### Testing
select wallet modal > Change > observe

### CODE REVIEW

**Comment by W3stside** [comment]
currently broken from a test due to import path changes - fixing

**Comment by W3stside** [comment]
@alfetopito @elena-zh @biocom @anxolin I will merge this soon as it's minor and working for me. So please review post merge and I can address things further afterwards

**Review by elena-zh — APPROVED** [review]
Changes look good to me. 
Thanks

**Review by alfetopito — COMMENTED** [review]
Good!

FYI, still missing #906 

screenshot_2021-07-19_10-24-47

I'd say we should fix it for the release

**Pull request merged**
