### PR TITLE
Profile page: Add vCOW swap feature cards

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

**🡒 Note: This is part of a waterfall PR series 🡐**

- Adds styled component (cards) to support the vCOW/COW token balance display and conversion.

**Desktop**

Screen Shot 2022-03-18 at 12 28 19

**Tablet/Medium resolutions**

Screen Shot 2022-03-18 at 12 28 03

**Mobile/small resolutions**

Screen Shot 2022-03-18 at 12 27 18

**No vCOW card container: Governance card falls in to place:**

Screen Shot 2022-03-18 at 15 34 34

**Only the COW balance:**

Screen Shot 2022-03-18 at 15 35 08

Just to demonstrate the sizing flexibility of the card elements.

---

**Light mode**

Screen Shot 2022-03-18 at 15 43 44

---

# Todo
- Style the unvested/vested tooltip further + light mode [?] icon
- Center page titles (Profile). Need to check as this affects all content pages.
- Style/create the governance card
- Cross browser/device tests

### CODE REVIEW

**Comment by fairlighteth** [comment]
Noticed on medium resolution, the COW balance token icon position/margin could be improved. Will handle in a up following PR (cc @elena-zh )

**Review by alfetopito — APPROVED** [review]

**Comment by alfetopito** [comment]
> Noticed on medium resolution, the COW balance token icon position/margin could be improved. Will handle in a up following PR (cc @elena-zh )

You mean this, right?
Screen Shot 2022-03-18 at 10 51 13

**Comment by fairlighteth** [comment]
@alfetopito Right, forgot that it would break the build, fixed now!

**Comment by elena-zh** [comment]
Hey @fairlighteth , changes LGTM now!
The only thing I'd like to mention, that it would be nice to make formatting of these amounts locale dependable 
image

Also, it would be nice to show full amounts on hover as we do for all amounts across the app
image

But I feel that everything I have mention is our of scope of the current task. 

Thanks!

**Review by elena-zh — APPROVED** [review]

**Comment by fairlighteth** [comment]
@elena-zh Thanks for reviewing again:
> The only thing I'd like to mention, that it would be nice to make formatting of these amounts locale dependable
> Also, it would be nice to show full amounts on hover as we do for all amounts across the app

Yes agreed, let's keep this in mind when the actual balances are connected (now hard coded).

**Comment by elena-zh** [comment]
@fairlighteth , I have created #2571 task for this

**Review by anxolin — APPROVED** [review]
Look great to me!

I only have two tiny nitpicks, which you can ignore.

One is, that i think in responsive, is more relevant the COW than vCow so it should be higher:
image


The other, is I kind of liked more your original proposal for the background of the vested amount. I agree with making it coherent, but maybe your proposed background was nicer than the one we had for the affiliate.

**Pull request merged**
