### PR TITLE
Update header button mobile part 1.

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Solution for highlighting CLAIMING on mobile

https://user-images.githubusercontent.com/31534717/149351278-9195f23b-f7b1-4420-a0b5-8f44ff3bd5c2.mov

Can be further iterated on in future PRs, by alternating between the three dots (...) and the vCOW token image

- Fly out menu CLAIM button now triggers the same function (history push /claim) vs triggering the original UNI function.

Todo:
- Styling of claim button in the fly out menu.

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
Is it possible this branch is very outdated?  it says "Claim vCOW" when latest PRs say "vCOW" only

Also, if i click the button it opens the menu


The highlight, u plan to add it always or only if you have claimings available?

**Comment by biocom** [comment]
> Is it possible this branch is very outdated? it says "Claim vCOW" when latest PRs say "vCOW" only

Was added on purpose. My thinking was the 'Claim' is more explicit and covers the purpose. But I caught up on the latest decision on that, so will update it in a follow up PR.

> Also, if i click the button it opens the menu

Hmm indeed, just noticed that. But fixed in this PR https://github.com/gnosis/cowswap/pull/2137


> The highlight, u plan to add it always or only if you have claimings available?

My initial plan was for it to highlight it **always**. As a user you may have your wallet connected or not. In all cases: A claim can be queried for any account other than your account. So my thinking was, we could highlight this feature for all users.

But open to only highlight it for **connected** wallets _and_ which at least have an active claim.

**Comment by biocom** [comment]
Consolidating waterfall. Review this PR at your convenience, post merge/consolidation.

**Comment by elena-zh** [comment]
Great changes! 
I posted several UI issues found in a separate ticket #2148

**Pull request merged**
