### PR TITLE
Added copy button to claiming account

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Copy button on claiming account
Screen Shot 2022-01-26 at 11 19 30

  # To Test

1. Go to claim, check for one account
* There should be a copy button next to the address in the top right

### CODE REVIEW

**Comment by biocom** [comment]
Nice one. Only things I found:
- We need some margin between 'copied' and the checkmark icon (on click)
- On mobile it pushes the other element around

https://user-images.githubusercontent.com/31534717/151241615-4e07765d-24f0-4503-8079-5bb8ef754d3c.mov

I say, low prio for now and I shall address these separately 👍🏼

**Review by fairlighteth — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @alfetopito , works fine!
In addition to @biocom comment, I should state that 'Copied!' moves 'Change account' button outside of the screen area in real mobile devices (both in Android and iOS)

https://user-images.githubusercontent.com/70885163/151335379-d8173d8a-4b25-493e-a616-18b58b4a7b15.mp4

**Review by anxolin — APPROVED** [review]
Code-wise approve!

**Comment by biocom** [comment]
Merging to see if I can address one of the style issues.

**Pull request merged**
