### PR TITLE
Don't call fee/price endpoint on Wrapping (ETH/WETH || XDAI/WXDAI etc)

### LINKED ISSUE #1853: Do not show fees warning when XDAI/ETH is selected as a Sell token
Reported in https://altoros.slack.com/archives/C025G521XQD/p1637069215012300
and https://gnosisinc.slack.com/archives/CPZA1AGKY/p1637074856111400

The warning is displayed below the section and is applied to the token pair a user selects in the From/To fields.

This issue came up in a research session a couple of days ago. The user thought (partially based on this warning) that when he wrapped ETH the swap would also go through.

It would be nice not to show  fees warning when XDAI/ETH is selected as a Sell token 
or
move this warning to the top
or
?

### LINKED ISSUE #1927: [1.5.0] Price and 'Free' fees fields appear for WETH/ETH token pair
1. Open the app
2. Do not connect a wallet
3. select WETH/ETH token pair

**AR**: Price and 'Free' fees fields appear 

**ER**: no Price and 'Free' fees fields appear  for this token pair

### PR DESCRIPTION
**Pull request by W3stside**
# Summary

Closes tech debt: dont call fee/price on wrapping op

Closes #1853 and closes #1927 

Dont call fee/price on wrapping operation, any chain

image

  # To Test

1. any chain
2. select native token IN/OUT
3. inverse = wrapped native
4. enter amount
5. check networks tab that no requests are made 
6. can still wrap etc

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
LGTM!

**Review by alfetopito — APPROVED** [review]
It is working fine.

Only caveat is that, when not connected, the behaviour is quite weird

I had another token selected as buy token.
The price loaded.
Then I picked ETH as the buy token and got this:
Screenshot from 2021-11-25 08-22-10

Switching around and manually changing the input resulted in `0` for the opposite
Screenshot from 2021-11-25 08-33-11

**Review by anxolin — COMMENTED** [review]
Thanks for the fix, it doesn't do the request anymore, but before merging I would review the case mentioned by @alfetopito , cause I think that's an undesired effect

Maybe is cause chainId is undefined? If that's the case, for the isWrapping check we should assume mainnet (as the app does)

**Comment by alfetopito** [comment]
I can still reproduce the issue when not connected.
Screenshot from 2021-12-03 12-27-20
Screenshot from 2021-12-03 12-27-03

And when connected I even got slippage :sweat_smile: 
Screenshot from 2021-12-03 12-26-17

**Comment by elena-zh** [comment]
Hey @W3stside , I still face issues mentioned above: 
image

image

Moreover, lots of strange numbers
image


See the video: https://watch.screencastify.com/v/jxR0fTCN0HxQVxdJHKr2

**Comment by elena-zh** [comment]
Steps to reproduce the issue with weird amounts:

**Comment by elena-zh** [comment]
Besides, there is another issue: currently, amount of a wrapped/unwrapped token shows 0 to a not connected user. See comparison with Prod
issue #1
issue #1-2

**Comment by W3stside** [comment]
right now when disconnected we dont show an output for a wrapping operation. on the flip side it no longer does the strange calcuation of a trade when swithcing to ETH from another token as outlined by Elena. 

it also gets rid of the fee / price messages when wrapping

**Comment by elena-zh** [comment]
Hey @W3stside , now  I do not see weird numbers. 
I found another edge case for fee request displaying, but I reported it in a separate ticket #1980 .
As for this issue https://github.com/gnosis/cowswap/issues/1920#issuecomment-987739185, I will report a separate low priority ticket for this.

**Pull request merged**
