### PR TITLE
Updated error message for `WrongOwner` api response

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Addressing https://github.com/gnosis/gp-swap-ui/pull/715#issuecomment-852186217

screenshot_2021-06-01_08-12-40

### CODE REVIEW

**Comment by michelbio** [comment]
Good. Would just break it down in two paragraphs (cut at 'Check whether your wallet.....' ).

**Review by biocom — APPROVED** [review]
Good. Would just break it down in two paragraphs (cut at 'Check whether your wallet.....' ).

**Comment by alfetopito** [comment]
> Good. Would just break it down in two paragraphs (cut at 'Check whether your wallet.....' ).

Well I agree.

The thing is, this is the exception message.
It was supposed to be short and concise.

It swallows new line characters. It'll need more stuff to get a better display and I don't think it's worth the effort right now.

**Comment by biocom** [comment]
> > Good. Would just break it down in two paragraphs (cut at 'Check whether your wallet.....' ).
> 
> Well I agree.
> 
> The thing is, this is the exception message.
> It was supposed to be short and concise.
> 
> It swallows new line characters. It'll need more stuff to get a better display and I don't think it's worth the effort right now.

What I thought too 👍🏼

**Review by anxolin — APPROVED** [review]
Nice!

Not sure if it works adding `\n` or `<br />`, agree, this is not too important although I thought the same as Michel when I saw it. 

If you use `\n` you fix how is shown just with css`whiteSpace: "pre-wrap"`

**Comment by alfetopito** [comment]
> Nice!
> 
> Not sure if it works adding `\n` or `<br />`, agree, this is not too important although I thought the same as Michel when I saw it.
> 
> If you use `\n` you fix how is shown just with css`whiteSpace: "pre-wrap"`

That worked!
screenshot_2021-06-02_09-44-48

**Pull request merged**
