### PR TITLE
Make links to open in new page

### LINKED ISSUE #1068: Track clicks in twitter, dev portal, or any external links
**Description**
Track clicks in twitter, dev portal, or any external address

* See notes in: https://gnosisinc.slack.com/archives/CSGLUC1BN/p1627378660040800

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Make all links in the FAQ to open in a new tab

Also, closes #1068

### CODE REVIEW

**Comment by elena-zh** [comment]
Hi @anxolin , 
I'm not sure if it is an intended behavior, but the last (and the only one) link that is not open its content in a new tab is a 'FAQ' link at the bottom of the 'About' page.
image

All the rest links work fine on 'FAQ', "Terms and conditions' and "About' pages

**Review by alfetopito — APPROVED** [review]
Is this something we want to track with analytics?

**Comment by avsavsavs** [comment]
> Is this something we want to track with analytics?

@alfetopito  Yes please, everything that is trackable, It would be great to know. This way we can analyze better what works and doesn't work

**Review by alfetopito — CHANGES_REQUESTED** [review]
As per Alex V's comment, please add analytics. I believe there's a component for that already.

**Comment by anxolin** [comment]
Although this was a PR meant as a "hotfix" with just the open in new tab thingy, I also added the requested analytics since i guess is low risks. Anyways, merging with it, but please @avsavsavs @michelbio do a review in case something is not right cuause this might go to production very soon

**Pull request merged**
