### PR TITLE
Update index.tsx

### PR DESCRIPTION
**Pull request by avsavsavs**
Fixing some words for the Pull 1715, all related to Smart Contract Signing. Basically, unified calling everything off-chain, and some minor word changes

# Summary

Expands Pull 1715

### CODE REVIEW

**Comment by anxolin** [comment]
@avsavsavs pls, either solve conflicts or recreate this PR against release/1.5

**Comment by avsavsavs** [comment]
Will recreate it in 1.5 @anxolin

**Comment by W3stside** [comment]
@avsavsavs can we close this? if so do so please

**Comment by anxolin** [comment]
I think this one is super old and the changes are already included. Closing. Alex, reopen if you feel we still need to apply any change

**Pull request closed without merging**
