### PR TITLE
[905] isLocalAware: false in formatSmart

### LINKED ISSUE #905: Locale number format not respected
**Description**
I would expect to see a dot (`.`) as decimal separator in the swap interface, but recently on staging this has changed to a `,` everywhere except in the price quote (circled in black on screenshot)

Note that this is only an issue on `Firefox` as far as I can tell.

Screenshot 2021-07-09 at 09 28 45

**How to Reproduce**

Not exactly sure how to explicitly reproduce but I can share my system preferences for local and possibly also my browser ones.

This is specifically happening only on Firefox.

Screenshot 2021-07-09 at 09 49 42

and could be that Firefox has open bugs it "WONTFIX" about how the system locale isn't respected.

**Expected behavior**
I would expect to see is what I see on the production environment (i.e. decimal separators everywhere)

Screenshot 2021-07-09 at 09 42 44

**Additional context**
Also, if it's relevant for the described bug, add information like the browser or OS.

### PR DESCRIPTION
**Pull request by W3stside**
Closes #905 based on UX from @bh2smith 

@bh2smith please test that it's working as expected

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Comment by W3stside** [comment]
@bh2smith can you please review this post merge? thanks!

**Comment by bh2smith** [comment]
Will review ASAP, do you happen to have the link where I can try it?

**Comment by W3stside** [comment]
> @bh2smith can you please review this post merge? thanks!

https://pr940--gpswapui.review.gnosisdev.com/

**Comment by bh2smith** [comment]
Looks fantastic @W3stside and works like a charm. My only worry from the code changes here are that users who prefer comma separated decimals might not be able to configure them. Is this true? In any case I will bookmark this PR and use it forever onward! 🥂

**Comment by W3stside** [comment]
maybe later we can add a config to change this but we'll leave it disabled

**Comment by alfetopito** [comment]
> Looks fantastic @W3stside and works like a charm. My only worry from the code changes here are that users who prefer comma separated decimals might not be able to configure them. Is this true? In any case I will bookmark this PR and use it forever onward! clinking_glasses

Those users will have to deal with it =P
Better to be consistent and use it throughout the same representation.

As for the PR bookmark, this change is coming in the next release, so it will be in staging soon :)

**Pull request merged**
