### PR TITLE
Orders Sidebar --> Slide in effect.

### PR DESCRIPTION
**Pull request by biocom**
# Summary

- Adds a slide in effect for the orders sidebar.
- Desktop -> slide from right to left.
- Mobile -> slide from bottom to top.
- Simplified props passing/potentially improve app perofrmance: Previously the orders sidebar was always rendered (while not being visible). Right now it's only rendered on user request. Less props required to being passed through.

https://user-images.githubusercontent.com/31534717/129740852-73ba37d6-530e-4bb4-a8b7-bec2cedacd68.mov

https://user-images.githubusercontent.com/31534717/129740877-640ad4e1-6a1c-4881-b52b-d280bb8cfcbc.mov

### CODE REVIEW

**Comment by MareenG** [comment]
I noticed that the menu(...) disappears on mobile devices (not reduced screen size only mobile devices) it is the same for #1269

**Review by alfetopito — COMMENTED** [review]
Slide in, but no slide out?

Also, I was ok without the animation in the first place, so I don't feel strongly about adding it now.

**Comment by elena-zh** [comment]
I see 2 scrolls (Win10 +Chrome, FF and Brave) when I open a side bar in the desktop version when screen resolution is 1536 x 864 and less
double scrolls
reduced

Could we do something with this?

**Comment by biocom** [comment]
> I see 2 scrolls (Win10 +Chrome, FF and Brave) when I open a side bar in the desktop version when screen resolution is 1536 x 864 and less
> double scrolls
> reduced
> 
> Could we do something with this?

Replied to this in another PR, but what we can do is add a 'noScroll' class to the `body` whenever the sidebar is opened. The `noScroll` class then applies 'overflow:hidden' to `body` while the sidebar is open. Will try to address in this PR.

**Comment by biocom** [comment]
@elena-zh Try my last commit when the build is finished.

**Comment by elena-zh** [comment]
Hi @biocom , looks great!
The only issue I'd like to mention, is that side bar scroll starts from the middle of it on a reduced screen in Win 10 (might be an edge case):
middle

Please let me know whether we can fix it here/leave as it is/or I need to create a separate issue for this case.

**Comment by elena-zh** [comment]
> I noticed that the menu(...) disappears on mobile devices (not reduced screen size only mobile devices)

Hi @MareenG , I found several related issues with this bottom bar in mobile/tablet devices and created a separate issue for this: #1275 . I include your case there.

**Comment by biocom** [comment]
@elena-zh Got a screen record. of the last screen? My first thought is that it is intended behavior, given the X close  container is 'sticky' on scroll. Perhaps on Windows it recognizes this and shows the scrollbar as your screenshot. But curious on a screen record of it.

**Comment by elena-zh** [comment]
@biocom , here it is https://drive.google.com/file/d/11JnfQv2bj-0JWOMTFGeb6NPu6AFeN52W/view

**Comment by biocom** [comment]
> @biocom , here it is https://drive.google.com/file/d/11JnfQv2bj-0JWOMTFGeb6NPu6AFeN52W/view

Thanks for this. I'd mark it as intended behavior, given on that resolution the sidebar becomes 'full overlay'. As mentioned the top element stays fixed. From my understand, the functionality (scrolling, sticky element, etc.) was fine?

**Comment by biocom** [comment]
> Slide in, but no slide out?
> 
> Also, I was ok without the animation in the first place, so I don't feel strongly about adding it now.

For now leaving it out: Right now on close, it actually removes the element from DOM. We'd have to have something like a 'before unmount' delay where it shows the slide out CSS effect.

**Comment by elena-zh** [comment]
> From my understand, the functionality (scrolling, sticky element, etc.) was fine?
Yes, this works fine.

**Review by elena-zh — APPROVED** [review]

**Review by alfetopito — APPROVED** [review]
As I said, not strongly pro or against it.

**Pull request merged**
