### PR TITLE
2440/uni merge

### LINKED ISSUE #2440: Merge Uniswap
You know the drill...

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #2440 

Merge with latest from original UNI code

WIP

  # To Test

1. <<Step one>> Open the page `about`
- [ ] <<What to expect?>> Verify it contains about information...
- [ ] Checkbox Style list of things a QA person could verify, i.e.
- [ ] Should display Text Input our storybook
- [ ] Input should not accept Numbers
2. <<Step two>> ...

  # Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

### CODE REVIEW

**Comment by JFrankfurt** [comment]
hi yes hello?

**Comment by tinaszheng** [comment]
why did all the uni people get a CLA request 😂

**Comment by alfetopito** [comment]
@JFrankfurt @tinaszheng and every other Uniswap contributor: sorry about that 😅 

Our CLA bot needs further work

**Comment by tinaszheng** [comment]
lol no worries. may i suggest checking out our [swap widget](https://docs.uniswap.org/sdk/widgets/swap-widget) component as an interface to the protocol instead of needing to fork and update the uni website? 😛

**Comment by W3stside** [comment]
Lmaoooo legendary moment

**Comment by alfetopito** [comment]
> **CLA Assistant Lite:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/gnosis/cowswap/blob/develop/docs/GNOSIS_CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> **0** out of **13** committers have signed the CLA.❌ @crowdin-bot❌ @tinaszheng❌ @JFrankfurt❌ @moodysalem❌ @callil❌ @uniyj❌ @ianlapham❌ @dependabot[bot]❌ @NoahZinsmeister❌ @zzmp❌ @willhennessy❌ @willpote❌ @justindomingueYou can retrigger the CLA Action by commenting **recheckcla** in this Pull Request

Sorry again everyone, a new push just triggered that...
Forgot to disable the bot first, my bad.

**Comment by alfetopito** [comment]
> **CLA Assistant Lite:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/gnosis/cowswap/blob/develop/docs/GNOSIS_CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> **0** out of **13** committers have signed the CLA.❌ @tinaszheng❌ @JFrankfurt❌ @moodysalem❌ @crowdin-bot❌ @callil❌ @uniyj❌ @ianlapham❌ @dependabot[bot]❌ @NoahZinsmeister❌ @zzmp❌ @willhennessy❌ @willpote❌ @justindomingueYou can retrigger the CLA Action by commenting **recheckcla** in this Pull Request

Sorry about that again. I forgot to disable the CLA workflow.
I have now removed it and you should not be bothered from now on.

**Comment by alfetopito** [comment]
Maybe the CLA bot messup is crewing the CI. It doesn't trigger any builds.
I'll close the PR an create a new one to see if that clear the stuck state or something.

**Pull request closed without merging**
