### PR TITLE
Handling exceptions on getBestQuote

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Handling exceptions on `getBestQuote`.

When either fee or price throws, return undefined for the respective promise.

screenshot_2021-07-09_12-58-35

### CODE REVIEW

**Comment by W3stside** [comment]
hmm this change shouldn't be required. the `promise.allFulfilled` returns an error object that we are (supposed to be) handling inside `_extractPriceAndErrorPromiseValues` - i want to take a look at this as well

**Comment by W3stside** [comment]
for me just removing the log on `L180` (as u did) solved it. Not really sure why that line was there in the first place. Returning `fee` and awaiting the whole thing just to log? 

Anyways it's the only required change as it stops throwing the entire function. Let's see what @anxolin thinks

**Comment by alfetopito** [comment]
> for me just removing the log on `L180` (as u did) solved it. Not really sure why that line was there in the first place. Returning `fee` and awaiting the whole thing just to log?
> 
> Anyways it's the only required change as it stops throwing the entire function. Let's see what @anxolin thinks

Forget about Anxo (for awhile =P)

I commented in the PR where that line was introduced but I was probably ignored :shrug: 

Anyway, hmm, yeah, only removing that could work too.
But then, we don't need to error handle the promises in this fn at all?

Also, the fee promise is awaited in the fn. If it fails, the whole call will fail.

**Comment by anxolin** [comment]
I'm also confused why this was needed. 
If there's an issue, it show throw and the error should be handled.

**Comment by W3stside** [comment]
> > for me just removing the log on `L180` (as u did) solved it. Not really sure why that line was there in the first place. Returning `fee` and awaiting the whole thing just to log?
> > Anyways it's the only required change as it stops throwing the entire function. Let's see what @anxolin thinks
> 
> Forget about Anxo (for awhile =P)
> 
> I commented in the PR where that line was introduced but I was probably ignored 🤷
> 
> Anyway, hmm, yeah, only removing that could work too.
> But then, we don't need to error handle the promises in this fn at all?
> 
> Also, the fee promise is awaited in the fn. If it fails, the whole call will fail.

I would go with removing the log and keeping the rest. that await function is handled in the `allFulfilled` call at the end properly. You can test it out by only removing the log and getting a token pair on rinkeby to throw insufficient liquidity

**Comment by alfetopito** [comment]
> I would go with removing the log and keeping the rest. that await function is handled in the `allFulfilled` call at the end properly. You can test it out by only removing the log and getting a token pair on rinkeby to throw insufficient liquidity

Alright alright, updated

**Review by W3stside — APPROVED** [review]

**Pull request merged**
