### PR TITLE
Feature/2008 percentage progressbar

### LINKED ISSUE #2008: Progress bar with percentages
**Description**

Create a progress bar component with percentages on top.
Clicking on the percentages should update the bar.

Screenshot from 2021-12-17 13-15-24

**Proposal**

This component will later be used in the claiming page.
The value will be read from and persisted to input state (to be defined).
Bar should be updated on percentage click as well as manual input change.

Maybe this state will be stored on redux? Still not defined.

For further context, this what what the surrounding page will look like:
Screenshot from 2021-12-17 13-34-05

**Additional context**
- Wireframes: https://www.figma.com/file/DPp3awAUcqpwpV1dD4wFB9/CoW-claiming?node-id=92%3A5718

### PR DESCRIPTION
**Pull request by maria-vslvn**
Fixes #2008 

Create a progress bar component with percentages on top.
Clicking on the percentages should update the bar.

  # Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

### CODE REVIEW

**Comment by maria-vslvn** [comment]
@ramirotw @elena-zh @alongoni i've added the progressbar component to the profile page, so you can check it at the bottom of the form

**Comment by elena-zh** [comment]
Hey @maria-vslvn , the progress bar looks good to me. 
The only think is that it has a default value = 33%, but there is no such number on it. So it would be nice to make it 0% or 100% for now... 
colors and 33%

Then, sometimes percentages on the progress bar seem to be hardly visible in the dark mode, however, I can't say that it is a priority as the bar will be placed into the 'black' form. 

Another case, that the bar size is not fixed when change percentages on it in a mobile view. So it would be nice to fix this. 

https://user-images.githubusercontent.com/70885163/147577748-b1e06cef-a5ac-41d6-83c9-35fe329d502f.mp4

**Review by alongoni — COMMENTED** [review]
Looks great Maria!!
Just an idea we can consider: What about if we hide the % value at the right of the progressbar and highlight the selected % vlaues at the top? 
A rough draft:
image

Also we can add border-radius: 16px and improve the background color:
image

**Comment by elena-zh** [comment]
Hey @maria-vslvn , @alongoni , I think we need to consider some kind of a design that will match this form, as the bar is going to be displayed there
image

**Comment by alongoni** [comment]
hey @maria-vslvn we can try something like this:
image

**Comment by alfetopito** [comment]
Maria, please reset your branch against `claim`. We are not yet merging the whole develop into it.
Then you just cherry-pick you changes.

Regarding the task scope/requirements, I'll update the base issue with more details.

**Comment by maria-vslvn** [comment]
@alongoni @alfetopito @ramirotw i've created a new branch from claim and a new pr, decided it could be better. also i tried to improve the bar a bit, so  you can check the bar here https://github.com/gnosis/cowswap/pull/2060

**Pull request closed without merging**
