### PR TITLE
[Claim] Input untouched errors

### PR DESCRIPTION
**Pull request by W3stside**
Alternative to Nenad's #2299

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @W3stside , the main issue that @nenadV91 was trying to solve in #2299 , is to not show this validation messages when fields are in the default state
image

But here we show them again.

**Comment by W3stside** [comment]
@elena-zh I thought based on your comment in that PR that we indeed wanted that?

**Comment by elena-zh** [comment]
Not exactly. 
My idea is not to show a user warning messages when a user opens the form for the 1st time, and have not yet entered any amount. 
So users can see the numbers/text, not red warnings. 
It is logical to see the warning text at the bottom of the page to me to explain why the 'review' button is disabled, but not repeatedly on every option.

**Comment by W3stside** [comment]
Closing!

**Pull request closed without merging**
