### PR TITLE
Fix CowGame page height and text mods.

### PR DESCRIPTION
**Pull request by biocom**
This fixes some aspects of https://github.com/gnosis/cowswap/issues/858

- Page jumps up when pressing space bar.
- Text changes (removed title to use less initial page height, to prevent jumpiness).

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
Unless I'm misunderstood the description, the page jumping that I mean is still there:

## before starting
screenshot_2021-07-06_10-59-15

## after starting
screenshot_2021-07-06_10-59-25

**Comment by biocom** [comment]
@alfetopito I distinguish between:

1. Page jump: Page as in viewport. Previously caused by the page content being sufficient large in height, causing the whole viewport to go from having a scrollbar vs no scrollbar -> thus page 'jumped'.
2. Game container 'jump': The container simply is reduced in height, because the 'Press Space to start' header is removed.

In my view no. 2 is not that disturbing. But I guess that's the one you meant?

**Comment by alfetopito** [comment]
> @alfetopito I distinguish between:
> 
>     1. Page jump: Page as in viewport. Previously caused by the page content being sufficient large in height, causing the whole viewport to go from having a scrollbar vs no scrollbar -> thus page 'jumped'.
> 
>     2. Game container 'jump': The container simply is reduced in height, because the 'Press Space to start' header is removed.
> 
> 
> In my view no. 2 is not that disturbing. But I guess that's the one you meant?

Yes, I meant `2`.

**Comment by biocom** [comment]
@W3stside merging in, to test the release. Still feel free to review post-merge.

**Pull request merged**
