### PR TITLE
[Hotfix - 1.6.1 :fire: ] - Fix for double QR code issue

### LINKED ISSUE #1787: [autoconnect] - wallet is not correctly connected and QR code remains
**Description**
Wallet is not correctly connected when adding a consecutive wallet via wallet connect. The QR code remains visible eventhough the wallet app shows that the wallet was connected. 
After closing the QR code and trying to connect the wallet again the wallet is connected with the wrong Logo. 
Related to #1680

**How to Reproduce**
1. Go to cowswap
2. Click on connect wallet and choose WC
3. scan QR code, etc..
4. Disconnect wallet
5. Repeat with a new wallet (not only another account but also another wallet provider) 
6. OR code is not closed, close it manually
7. Close modal 
8. try to connect again via WC
9. Wallet is autoconnected but displays the wrong logo #1788 

**Expected behavior**
Connecting a consecutive wallet via WC should be as smooth as adding it for the first time

**Screenshots**
Current issue
https://user-images.githubusercontent.com/34510341/140505618-eb5cf1e9-123d-4340-952b-cd677bc3acfd.mov

1. Connecting with safe
2. Then disconnecting the Safe
3. trying to connect a new wallet(Trust) with WC (0:22-0:40) - The trust app showed that I am connected
4. But QR code remains and cowswap shows that I am not connected
5. Trying to connect again --- auto connected with the Safe which I disconnected before

As comparison in production: 

https://user-images.githubusercontent.com/34510341/140505896-7029e466-8f88-40d7-a9ed-3f615a3a2f49.mov

**Additional context**
See slack conversation 
https://gnosisinc.slack.com/archives/C025G521XQD/p1636037993009000

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #1787

Fixes issues with double QR code by updating @web3-react/walletconnect-connector to new version and adding fix for some additional issues that occur after the update like missing balances and wallet info.

### To test
- We should test issues mentioned in #1787,  #1929 and #1930 with the steps to reproduce
- We should also test other functionality around WalletConnect and QR code

### CODE REVIEW

**Comment by W3stside** [comment]
version name is outdated, please change this to reflect the current prod version and make sure everything is up to date. have you properly tested this? 

can you provide detailed testing steps to make sure we catch any bugs and avoid what happened last time? @nenadV91

**Comment by elena-zh** [comment]
Hey @nenadV91 , the #1923 issue is still not fixed in this PR

**Comment by nenadV91** [comment]
@elena-zh 
The issue with the disconnect from the wallet side should be fixed now.
Regarding MM wallet, I just tried DAI->OWL, WETH->PAX on Rinkeby and it works fine. 
I did notice some issues with the MM wallet last week also so could be that, maybe try again.

**Comment by elena-zh** [comment]
Hey @nenadV91 , changes LGTM besides an issue that is not related to this PR #1987 (co I can't test changes in Mainnet)
Also, connection is lost when change wallets, but we agreed to leave it as it is https://github.com/gnosis/cowswap/pull/1921#issuecomment-986697313

**Review by elena-zh — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @nenadV91 , the #1987 issue seems to be fixed. 
However, I have noticed that it is impossible to sign an order when connected to 1Inch wallet in this PR
impossible to sign

I thought it was related to #1987, but it appeared that not. Could you please take a look into it?

Thanks

**Review by anxolin — COMMENTED** [review]
From my side, code-wise seems alright to me. I would give my APPROVE if you get the approve from QA

I believe you have one unaddressed comment regarding 1inch

**Comment by nenadV91** [comment]
@anxolin I've posted about that in Slack https://gnosisinc.slack.com/archives/C025G521XQD/p1639403809006300, I don't have an iphone yet to debug this. I've tried browserstack but I think I need apple id to install new apps from the app store.

**Comment by W3stside** [comment]
should we close this? @nenadV91

**Comment by anxolin** [comment]
I thought this one was in production. can you confirm @nenadV91?

**Comment by elena-zh** [comment]
No, the issue is not in Prod. We could not release it due to [1Inch issue](https://github.com/gnosis/cowswap/pull/1945#issuecomment-992460679)

**Comment by nenadV91** [comment]
As Elena said this is not in Prod since there is still issue with 1inch wallet

**Comment by anxolin** [comment]
@nenadV91, i change this into develop branch for whenever we resume it

**Comment by anxolin** [comment]
@nenadV91 any update on this?

**Comment by nenadV91** [comment]
@anxolin Nope

**Pull request closed without merging**
