### PR TITLE
Adapt URL of gnosis safe to unified version

### LINKED ISSUE #1849: [1.5.0] Firefox: View Gnosis safe link redirects to safe balances
The issue might be related to Gnosis safe itself

**Steps**: 
1. Open Cowswap in Firefox
2. Connect a gnosis safe
3. run a transaction
4. Press on the View Gnosis safe link in the Activity modal

**AR**: user is redirected to the 'Balances' safe section
https://watch.screencastify.com/v/71F6IsMg3pNnMocVCoaA

**ER**: user should be redirected to the Transactions section

### PR DESCRIPTION
**Pull request by anxolin**
# Summary
Closes #1849
Adapts to the new URL structure for gnosis Safe after the unification deployed today

image

Now URLs look like this:
https://gnosis-safe.io/app/rin:0x951D3d754abdB5182815e3E43d55eD3433b52522/transactions/history

# To Test

1. Links to the Gnosis Safe for the tree networks

### CODE REVIEW

**Review by MareenG — CHANGES_REQUESTED** [review]
It currently links to the Safe transaction queue but shouldn't it link to the transaction history?

**Comment by elena-zh** [comment]
@MareenG , safe URL does not have a separation between 'queue' and 'history' tabs, so it is impossible to navigate exactly to the history. 
https://us02web.zoom.us/j/87568027224?pwd=MEdyeThTRWtnL01aMWZrRjF1NmRjdz09
The only thing we can do is to suggest Gnosis Safe team to separate these URLs to 
 - /transactions#queue
 - /transactions#history

And then we will be able to redirect directly to the History.

**Comment by MareenG** [comment]
> @MareenG , safe URL does not have a separation between 'queue' and 'history' tabs, so it is impossible to navigate exactly to the history. https://us02web.zoom.us/j/87568027224?pwd=MEdyeThTRWtnL01aMWZrRjF1NmRjdz09 The only thing we can do is to suggest Gnosis Safe team to separate these URLs to
> 
> * /transactions#queue
> * /transactions#history
> 
> And then we will be able to redirect directly to the History.

But when you click on the link Anxo provided it directs you to the history. 
https://gnosis-safe.io/app/rin:0x951D3d754abdB5182815e3E43d55eD3433b52522/transactions/history
Whereas the link in the PR directs you to the queue 
https://gnosis-safe.io/app/rin:0x6EB8Ee3c042606dae355fCD4f9370C28f019Fb19/transactions/queue

**Comment by elena-zh** [comment]
@MareenG , got it, thank you! I have a previous version installed to my PC and did not notice that they had already changes routs. 
Sorry about that

**Comment by anxolin** [comment]
@MareenG I send to the queue on porpouse. 

This will change once they implement https://github.com/gnosis/safe-react/issues/970

I have to choose queue or history, i choose queue because is more relevant to me to send the users to sign while the tx needs more signatures than seeing it in the history

**Comment by anxolin** [comment]
Guys, i will need to merge this to mege in Barn. I address comments if u have more

**Comment by elena-zh** [comment]
I would suggest to separate cases when we may navigate users to the /queue or the /history pages. 
I have created a separate issue for this #1877

**Comment by anxolin** [comment]
> I would suggest to separate cases when we may navigate users to the /queue or the /history pages.
I have created a separate issue for this #1877


Yes is a good point. I will do as separate PR

**Pull request merged**
