### PR TITLE
ABOUT REBRANDING - NOT TO MERGE UNTIL ANNOUNCEMENT

### PR DESCRIPTION
**Pull request by avsavsavs**
Not to merge or apply this PR until rebranding announcement is done. This will be done on January 4th if everything goes according to schedule.

This PR rebrands all mentions of Gnosis Protocol or GPv2 to CoW Protocol & CowDAO.

Summary
Doesnt fix any previous issue, just rebrands the names

Changing all the names from Gnosis to CoW. At least the text ones, not links.

### CODE REVIEW

**Comment by elena-zh** [comment]
LGTM!

**Comment by W3stside** [comment]
@avsavsavs do we need #2022

**Comment by avsavsavs** [comment]
yes @W3stside, one #2022 is for the FAQ, and #2024 is for the ABOUT

**Comment by W3stside** [comment]
Ok can you rename the titles to reflect better what they're doing? Thanks!

**Comment by avsavsavs** [comment]
yeah, my bad. Rename to add FAQ - ABOUT to each one

**Review by alfetopito — APPROVED** [review]

**Pull request merged**
