### PR TITLE
Claim style improve 20

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Styling of investing summary table
- Progress bar styling
- Replace GNO icon with more recent one
- Adding xDAI logo image. Needs to be linked up with @alfetopito PR where he commented xDAI out for now.
- General image compression

https://user-images.githubusercontent.com/31534717/150344421-5efbbf91-65b7-4f9c-bda9-4214faecc680.mov

Screen Shot 2022-01-20 at 14 06 31

### Todo:
- Improve styles a bit more on the summary table. Mainly spacing things out. 
- Decide on what content to show. I suggested to inform the user on each investment, that they cannot invest the remaining amount after claiming. This is only shown on <100 or >0 percentage numbers.

Screen Shot 2022-01-20 at 14 07 05

### CODE REVIEW

**Comment by biocom** [comment]
Noticed the `%` string missing in the progress bar, when on the investing summary (last) page.

**Comment by biocom** [comment]
> Noticed the % string missing in the progress bar, when on the investing summary (last) page. This happens only on smaller percentage numbers.

A fix has been pushed to solve for this:

**Comment by elena-zh** [comment]
Hey @biocom , will it be fixed when responsive views are implemented?
image

**Comment by biocom** [comment]
When you selected an investment, but end up not investing at all
Screen Shot 2022-01-20 at 14 23 11

we could still show the row. But then emphasize that you won't be able to invest later. Something like this message:
Screen Shot 2022-01-20 at 14 23 39

And perhaps hide the progress bar (when 0%).

What do you think?

**Comment by elena-zh** [comment]
I would disable 'Review' button when one of the selected options has 0 amount.. 
image

And one of the selected options does not have an 'approved' token

**Comment by elena-zh** [comment]
Could we please round this amount to 2 decimals? 
image

**Comment by elena-zh** [comment]
Also, I still think that it would be great to make this text left-aligned
image

**Comment by alfetopito** [comment]
> When you selected an investment, but end up not investing at all Screen Shot 2022-01-20 at 14 23 11
> 
> we could still show the row. But then emphasize that you won't be able to invest later. Something like this message: Screen Shot 2022-01-20 at 14 23 39
> 
> And perhaps hide the progress bar (when 0%).
> 
> What do you think?

This will not be possible when we implement the proper validations, so don't worry about handling it as a special case

**Review by alfetopito — APPROVED** [review]
Looks awesome!

I say we merge as is (after rebasing against `develop`) and I can address the pending code related comments in a follow up PR

**Review by anxolin — COMMENTED** [review]
❤️ pretty!

**Pull request merged**
