### PR TITLE
FAQ: Fixed some typos and did minor phrasing edits.

### PR DESCRIPTION
**Pull request by harisang**
# Summary

- Corrected a few typos in FAQ.
- Did some minor edits in some phrases.
- Removed all apostrophes (such as "it's", "you've", etc) as I I think they look a bit too informal.

QUESTION: In Lines 382, 621, 660, we use the word ```offline```. Should this be ```off-chain``` instead?

### CODE REVIEW

**Comment by W3stside** [comment]
@harisang please add reviewers on PRs.

Thanks for making this

**Review by W3stside — APPROVED** [review]

**Comment by elena-zh** [comment]
Could I get a preview link for this PR?

**Comment by W3stside** [comment]
CI is stuck, will attempt a force restart @elena-zh

**Review by elena-zh — APPROVED** [review]
LGTM!

**Pull request merged**
