### PR TITLE
Fix 404 for OPYN_LIST url (their file name changed)

### PR DESCRIPTION
**Pull request by fadomire**
# Summary
there is a 404 when requesting the opyn-tokenlist

they changed their filename in this commit:
https://github.com/opynfinance/opyn-tokenlist/commit/409fdc84dd827b8e94643b33baea6c10d93f51c5

This PR update the previous url with the new one

### CODE REVIEW

**Comment by fadomire** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by alfetopito — APPROVED** [review]
Looks good:

Screen Shot 2022-02-22 at 16 29 04
Screen Shot 2022-02-22 at 16 28 44

I mean, we have to work a bit on the contrast for dark mode, but it works as expected :)

**Comment by alfetopito** [comment]
Thanks for the contribution by the way :)

**Review by anxolin — APPROVED** [review]
Thanks for the contribution! it works, however, why Opyn list don't include the image of the token?

image


Can you make sure they change their list to include `logoURI`? Check out  this example https://raw.githubusercontent.com/SetProtocol/uniswap-tokenlist/main/set.tokenlist.json

**Pull request merged**
