### PR TITLE
Move affiliate banner to the top in Profile page

### PR DESCRIPTION
**Pull request by ramirotw**
# Summary

Close https://github.com/gnosis/cowswap/pull/2329

Fixes the Affiliate banner being displayed below the new Profile card

image

image

### CODE REVIEW

**Review by henrypalacios — APPROVED** [review]
Done!

**Review by elena-zh — APPROVED** [review]
Great job!

**Comment by anxolin** [comment]
Thanks for this! should this be cherry picked to `release/1.10` that's going live next week?

**Comment by ramirotw** [comment]
> Thanks for this! should this be cherry picked to `release/1.10` that's going live next week?

Sorry @anxolin the notification got hidden in the mails. I've just cherry-picked this onto `release/1.10`

**Pull request merged**
