### PR TITLE
Add coingecko list

### PR DESCRIPTION
**Pull request by anxolin**
Not 100% sure if we should merge, in local it was having some sluggish behaviour. 

This coingecko list is huge! and the token logic is inneficient. We should see if uni-v3 improves or maybe we can do sth ourselves. 

Anyways, I want to see if the PRODUCTION version has better performance.

### CODE REVIEW

**Comment by biocom** [comment]
Some observations:
- 404 with `https://pr802--gpswapui.review.gnosisdev.com/locales/en-US.json` (perhaps unrelated, just noting it down)
- Should we also enable Coingecko in the list?
Screen Shot 2021-06-24 at 13 40 50
- In general the app initially felt a bit sluggish (Brave) then on Firefox it seemed 'OK'.

**Review by biocom — APPROVED** [review]

**Comment by anxolin** [comment]
I'm reluctant to merge this, it's noticeable less usable, more sluggish. I can see that Uni itself disabled the list

I think is best to look for alternative solutions:
- Endpoint for big lists. I would probably suggest a simple API used as a last resource where there's no tokens matching a name/symbol/address. 
- Improve efficiency of lists in the UI:
   - Don't break if the list get's to big. It's even an attack vector where someone can do a DOS
   - More efficient rendering. The reduce function and logic looks very inefficient

Any other ideas?

**Comment by alfetopito** [comment]
Not a big fan of adding it back.
Couldn't we maybe improve how that's stored/accessed to make it more performant?
This is not a huge 1M records thing, the app should be able to handle a couple of thousand entries without slowing down :/

I know I know, inherited code.

**Comment by W3stside** [comment]
also not a huge fan of adding it back...

**Comment by anxolin** [comment]
Related to this issue. 

https://github.com/gnosis/cowswap/issues/803

I will close the PR without merging. We can see what to do when we address it.

**Pull request closed without merging**
