### PR TITLE
Iterate success page post merge.

### PR DESCRIPTION
**Pull request by biocom**
# Summary
Screen Shot 2022-01-26 at 12 58 00

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
Nice!

I paste the other relevant screenshot. When you claim for someone else

image

**Comment by W3stside** [comment]
should we show full claim amount (not smart) here?

**Comment by biocom** [comment]
> should we show full claim amount (not smart) here?

@W3stside Open to both. Not sure how long that number can get (showing in full). Can take it on a different PR as long as we're in line with the ClaimSummary amount on the first page.

Merging as discussed.

**Comment by elena-zh** [comment]
LGTM!
The only strange thing I noticed that a claimed amount disappears when go back to the Claimed page. 
I reported it here https://github.com/gnosis/cowswap/issues/2219#issuecomment-1022210281

**Pull request merged**
