### PR TITLE
Shadow/slider.

### PR DESCRIPTION
**Pull request by biocom**
# Summary

- Adds a small shadow on the right to indicate horizontal scrolling.
- Adds right padding to push the last token/makes it better selectable.

https://user-images.githubusercontent.com/31534717/127314999-bcd6c20d-6822-42bf-919a-06bc4a7f1f01.mov

- Currently not touching the height of the container, as I believe I addressed this in a separate PR already (to prevent conflicts).

### CODE REVIEW

**Comment by elena-zh** [comment]
HI @biocom , great job!
Still, I'm able to catch UI issues in iPhone: 'shadow' is too white in the dark mode iOS
image

Besides, it is impossible to select a token by clicking on a shadowed area. I'm not sure, if it is an expected or not..
image

**Comment by biocom** [comment]
Investigating now.

**Comment by biocom** [comment]
Had some Safari issues (https://css-tricks.com/thing-know-gradients-transparent-black/) around the gradient, but fixed now. The shadow itself is 'not' clickable anymore and thus you can select a token as usual.

https://user-images.githubusercontent.com/31534717/127331684-61753eb6-c3e9-4f04-8233-6ee30830bb99.mov

**Review by elena-zh — APPROVED** [review]
LGTM!

**Review by W3stside — APPROVED** [review]
nice! would be cool to end the shadow on the last token but that sounds too hard for little gain.

**Comment by biocom** [comment]
@W3stside Try now?

**Pull request merged**
