### PR TITLE
[CLAIM] Button refactor and error fix

### PR DESCRIPTION
**Pull request by W3stside**
# Summary

Refactors the NavButtons to a new component and makes it easier to read
Blocks button when ONLY paid are claimable but not selected

Screenshot
image

  # To Test
1. use this accoutn: 0x97EC4fcD5F78cA6f6E4E1EAC6c0Ec8421bA518B7
2. see that when nothing is selected it cannot be progressed
3. noice

### CODE REVIEW

**Comment by elena-zh** [comment]
@W3stside , I can't open the preview link. Can you?
image

**Comment by elena-zh** [comment]
Nevermind, it reloaded in a minute or so... 🤨

**Comment by elena-zh** [comment]
Changes LGTM!

**Review by elena-zh — APPROVED** [review]

**Comment by W3stside** [comment]
feel free to review after

**Pull request merged**
