### PR TITLE
Icons on activity details for claim

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

* Added vCOW token on claim txs
* Added USDC and GNO tokens to rinkeby and gchain
* Removed unused components/images

  # To Test

1. Do approvals for GNO and USDC on rinkeby and gchain
* Activity history should have image for them
2. Do a claim on any network
* Activity history should have vCOW token image

# Note

GNO looks pretty bad on light mode and vCOW doesn't look good in either mode

| Screen Shot 2022-01-28 at 16 23 24 | Screen Shot 2022-01-28 at 16 23 03 |

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Hey @alfetopito , token icons are displayed in the activity modal now. 
And yes, I agree that we should make vCOW icon more visible in the light theme, as well as GNO icon in the dark theme. 
Maybe @biocom could help with this?

**Comment by biocom** [comment]
Addressing the vCOW icon in #2357

**Review by anxolin — APPROVED** [review]
Great, other than GNO looking like this in darkmode: 

image

...but i think michel is looking into that

**Comment by anxolin** [comment]
Merging, since the other issues are being addressed in a different PR

**Pull request merged**
