### PR TITLE
Update gnosis chain logo

### LINKED ISSUE #2065: Update logos for Gnosis chain according to the media-kit
Originally reported in  https://github.com/gnosis/cowswap/pull/2023#issuecomment-1008832103

Additionally to the written name changes, can we also update the corresponding logos to this ones: https://www.xdaichain.com/media/media-kit

### PR DESCRIPTION
**Pull request by alongoni**
# Summary

Fixes #2065 
image
image

  # To Test

1. Open the [Cowswap dApp](https://pr2073--gpswapui.review.gnosisdev.com/). And check the  Gnosis Chain logo in the network selector.

### CODE REVIEW

**Comment by alongoni** [comment]
Regarding the token list logos. We need to update the WXDAI logo?
image
We are consuming this logo from [/1Hive/default-token-list](https://raw.githubusercontent.com/1Hive/default-token-list/master/src/assets/xdai/0xe91d153e0b41518a2ce8dd3d7944fa863463a97d/logo.png)
image
Maybe we can request a change here:

https://github.com/1Hive/default-token-list/issues/new?assignees=&labels=token+request&template=token-request.md&title=Add+%7BTOKEN_SYMBOL%7D%3A+%7BTOKEN_NAME%7D

WDYT @alfetopito @avsavsavs

**Comment by alfetopito** [comment]
> Regarding the token list logos. We need to update the WXDAI logo? 
> 
> We are consuming this logo from [/1Hive/default-token-list](https://raw.githubusercontent.com/1Hive/default-token-list/master/src/assets/xdai/0xe91d153e0b41518a2ce8dd3d7944fa863463a97d/logo.png) image
> 
> Maybe we can request a change here: https://github.com/1Hive/default-token-list/issues/new?assignees=&labels=token+request&template=token-request.md&title=Add+%7BTOKEN_SYMBOL%7D%3A+%7BTOKEN_NAME%7D
> 
> WDYT @alfetopito @avsavsavs

I think the xDai logo just need to be set as the native currency logo for the Gnosis Chain network.
Now about wxDAI... yeah, we need to figure that out. I'll raise this internally.

**Review by alfetopito — APPROVED** [review]
Good to go, we can address the xDai/wxDai logo in another PR

**Comment by elena-zh** [comment]
Btw, we have a separate issue for the xDAI token logo on the board: #1179 . 
I added a comment there.

**Review by elena-zh — APPROVED** [review]
LGTM!

**Pull request merged**
