### PR TITLE
Fee subsidy modal styles

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Style enhancements for the fee subsidy modal
- Fixes issue https://github.com/gnosis/cowswap/issues/2560
- Fixes issue https://github.com/gnosis/cowswap/issues/2561
- Disables onClick for the tooltip (i) icon. Instead keeps it as a normal tooltip hover.
- COW icon replaced with the most recent SVG version (updated anywhere where Component `CowProtocolLogo` is imported).
- The X close in the modal has been made more modular for re-use purposes.

## Current
Screen Shot 2022-03-24 at 16 33 39

## New
https://user-images.githubusercontent.com/31534717/159965198-34f9fa76-e7d9-4c29-8e0e-4f8101c86a3f.mov

## New: Mobile
Screen Shot 2022-03-24 at 16 17 54

## New: Desktop => Light Mode
Screen Shot 2022-03-24 at 16 42 45

### CODE REVIEW

**Review by anxolin — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @fairlighteth , great changes!

Some minor issues: 
1. The table has square boarders in iOS 15.3
image
image

2. Might be considered as a nitpick, but it seems that the highlighting exceeds the boarders of the table. Is it done intentionally?
image

**Comment by elena-zh** [comment]
3. Also, when highlighted, there is no boarder between columns
image

**Comment by elena-zh** [comment]
Also, I noticed that the modal is displayed at the bottom of the screen in iPad mini with iOS 15.3.1 in Safari browser in the portrait mode
image

**Review by elena-zh — APPROVED** [review]
@fairlighteth , changes LGTM now. 
Thank you!

**Pull request merged**
