### PR TITLE
[1053] Re-enable common bases

### LINKED ISSUE #1053: [v0.17] Re-enable "common bases"
**Description**
We disabled "common bases" in the currency selector modal a few versions ago. I think it's a useful feature that allows users to quickly select a common token

**Proposal**
Literally just uncomment 2 lines. Potentially add more tokens we would consider "common" - no idea on the legal implication here though. 

What it would look like:
image

### PR DESCRIPTION
**Pull request by W3stside**
Closes #1053 

# Summary

Re-enables common tokens known as common bases in Uni. It shows to the user an opinionated list of common tokens used to trade above the token list for easy of token selection.

image

  # To Test

1. open the currency picker
2. make sure the hover actions / colours look good
3. select a token and make sure that for the same input type the selected token, if in the common tokens list, is displayed as disabled

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Changes LGTM!
The only thing to mention is that list of tokens is named as 'Common tokens' while section name in Uniswap is 'Common bases'. 
image

**Comment by W3stside** [comment]
> Changes LGTM!
> The only thing to mention is that list of tokens is named as 'Common tokens' while section name in Uniswap is 'Common bases'.
> image

yes, i explicitly changed this as "bases" means nothing in most people's context. I think "tokens" is more natural. open to changes obv

**Comment by alfetopito** [comment]
I suggest removing ETH from the list, at least on sell input.
- It's already the first entry by default
- We don't natively support trading it, so, avoid sending the wrong message

**Comment by W3stside** [comment]
> I suggest removing ETH from the list, at least on sell input.
> 
> * It's already the first entry by default
> * We don't natively support trading it, so, avoid sending the wrong message

fixed 2c5de8f

**Comment by biocom** [comment]
Looks good. One point of attention is mobile, where the amount of available space to scroll is very limited:

Screen Shot 2021-07-27 at 13 52 19

A suggestion would be to do something like you did with the confirmation modal:

https://user-images.githubusercontent.com/31534717/127150199-b8d51bcc-3dae-4913-88b8-a67281fda00b.mov

Can address later, unless you do it. Notes:
Screen Shot 2021-07-27 at 14 03 02
Screen Shot 2021-07-27 at 14 02 41

**Comment by W3stside** [comment]
@biocom good advice. i think seeing how much @alfetopito hates horizontal scroll i'll go for a dropdown or sth.

**Comment by biocom** [comment]
> @biocom good advice. i think seeing how much @alfetopito hates horizontal scroll i'll go for a dropdown or sth.

On mobile they call it a 'horizontal slider' 😄 - perfectly fine IMO.

**Comment by alfetopito** [comment]
> @biocom good advice. i think seeing how much @alfetopito hates horizontal scroll i'll go for a dropdown or sth.

I don't know where you got that impression.
I guess you are just offloading your frustration on me =P

Anyway, I think this occasion it's fine.

**Review by alfetopito — APPROVED** [review]
Ok with me, and I "allow" you to use an horizontal slider on mobile ;)

Already approved for when you do so

**Comment by W3stside** [comment]
> > @biocom good advice. i think seeing how much @alfetopito hates horizontal scroll i'll go for a dropdown or sth.
> 
> I don't know where you got that impression.
> I guess you are just offloading your frustration on me =P
> 
> Anyway, I think this occasion it's fine.

loooooool:
1. https://github.com/gnosis/cowswap/pull/760#issuecomment-862376232
2. https://github.com/gnosis/cowswap/pull/661#issuecomment-845266003

**Comment by alfetopito** [comment]
> > > @biocom good advice. i think seeing how much @alfetopito hates horizontal scroll i'll go for a dropdown or sth.
> > 
> > 
> > I don't know where you got that impression.
> > I guess you are just offloading your frustration on me =P
> > Anyway, I think this occasion it's fine.
> 
> loooooool:
> 
>     1. [130/faq #760 (comment)](https://github.com/gnosis/cowswap/pull/760#issuecomment-862376232)
> 
>     2. [Update index.tsx with CowSwap Table Interactions #661 (comment)](https://github.com/gnosis/cowswap/pull/661#issuecomment-845266003)

**Comment by biocom** [comment]
Addressed @alfetopito 's fav feature here: https://github.com/gnosis/cowswap/pull/1082

**Pull request merged**
