### PR TITLE
(bugfix) Terms and conditions styles

### LINKED ISSUE #1891: [Dev] Styles of Terms and Conditions section are changed in 10-22 questions
Related to #1860 
Styles of Terms and Conditions section are changed in 10-22 questions:

### PR DESCRIPTION
**Pull request by alongoni**
# Summary
Fixes #1891 #1860
Before:
image
After:
image

  # To Test

1. <<Step one>> Open the page [Terms and Conditions](https://pr1894--gpswapui.review.gnosisdev.com/#/terms-and-conditions)

### CODE REVIEW

**Comment by alongoni** [comment]
I've found that we have some inline html tag in the markdown. We should replace links, underline styles and also add ## Headings insted of usign ** for all titles.
image
https://github.com/DavidAnson/markdownlint/blob/v0.24.0/doc/Rules.md#md033

**Review by elena-zh — APPROVED** [review]
Changes LGTM!

**Review by alfetopito — APPROVED** [review]
BTW, I also pushed a commit removing some double white spaces from the code.

**Comment by alfetopito** [comment]
> I've found that we have some inline html tags in the markdown. We should replace links, underlined styles and also add ## Headings instead of using ** for all titles. image https://github.com/DavidAnson/markdownlint/blob/v0.24.0/doc/Rules.md#md033

Unless this is something that's little effort, I wouldn't worry about that right now, not really a priority.

**Pull request merged**
