### PR TITLE
Hotfix/1.10.1 - Enable claiming in prod

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

- Enable claiming in prod
- Cherry-pick some commits from develop

## Changelog

```git log --oneline origin/hotfix/1.10.1...origin/master --no-decorate```

60cfffe7b 2382/already claimed (#2394)
1ab7b5b74 Removed Ethereum word from popup text msg (#2412)
c7ba6d47c Show claimed context when already claimed (#2410)
56311fbc8 Update vcow blog links based on chain id (#2408)
66ed3cb98 Show banner if the user has claimed already (#2393)
d65d7f0ca Get deployment time per network (#2407)
8e3ae449c Update contract
c77062620 Updated gas estimation for gchain (#2391)
0e0ebae9e Improve responsiveness of header elements. (#2376)
72d923e10 Add alternative claim success sound. (#2384)
0cab01868 remove unused audio. (#2348)
5586fe984 Fix token display in dark/light mode for transactions. (#2386)
6e9d5210d Enable claiming on prod and ens

### Todo

- [ ] Change smart contract address for vCOW: Both for Gnosis Chain and mainnnet
- [x] Blog post link

### CODE REVIEW

**Comment by elena-zh** [comment]
I retested changes for

- Fix token display in dark/light mode for transactions. (#2386)
- remove unused audio. (#2348) 
- Add alternative claim success sound.
- Improve responsiveness of header elements.

And these changes LGTM there.
I can't retest changes for `'Enable claiming on prod and ens'`  as it will be visible to me in Prod env-t only.
In order to test this feature `Updated gas estimation for gchain` as well as regression tests on other claims, I need a new contract updated.

**Comment by elena-zh** [comment]
Weird things are happening in this PR: I stop seeing investment options for an account when I switch to another network, then return back. 
See the video: https://watch.screencastify.com/v/AyFi3IDgzEM1hFckds9c

**Review by anxolin — APPROVED** [review]

**Comment by elena-zh** [comment]
> Weird things are happening in this PR: I stop seeing investment options for an account when I switch to another network, then return back. See the video: https://watch.screencastify.com/v/AyFi3IDgzEM1hFckds9c

Fixed now. 

Also, I was not able to run tests for `Updated gas estimation for gchain` as GC deployment data was not updated, so I'm able to see only Rinkeby investment claims in this PR. 

All the rest changes LGTM.

**Review by alfetopito — APPROVED** [review]
Everything looks good.

Needed for the release:
1. vCOW contract address for all networks
2. Double check blog posts are correct

**Comment by anxolin** [comment]
Awesome! Big day tomorrow 🎉

**Review by elena-zh — APPROVED** [review]
LGTM!
I have found a new UI issue in the PR #2415, but it might be addresses later.

**Pull request merged**
