### PR TITLE
Release/v0.14.0 rc.0

### PR DESCRIPTION
**Pull request by biocom**
# Release notes
- Improve styling/markup for policy pages (also DarkMode related)
- Update Secure to use & fee model questions
- Show loading status (Cow Animation) when fetching/computing prices.
- FAQ: Included the question "Why is Cowswap a META DEX Aggregator?"
- Error handling: add quoteError state
- Soft and Hard loading states with the nose picking cow animation.

# Changelog
32e713a4 [Loading] Base PR with Nose Picking Cow and Hard load (#735)
dd320851 [Error Handling] - Base PR (#745)
774773cc Include one new FAQ Question under "General" (#754)
5f67b732 [Swap] Show loading status when computing (#668)
f7031cb3 Update feature_request.md
da59d89b Update bug_report.md
bfb9096a Update Secure to use & fee model questions (#719)
f707cb42 Improve styling+markup for policy pages. (#707)
3199d215 Remove target blank for policy menu links. (#705)

### CODE REVIEW

**Comment by W3stside** [comment]
@biocom can you change the description to match the others, especially with the commit history? thanks

**Comment by W3stside** [comment]
merging release candidate

**Comment by W3stside** [comment]
@biocom creating a fresh branch named appropriately for ease: 0.14.0

**Comment by anxolin** [comment]
Nice

**Pull request merged**
