### PR TITLE
Fix issue with lint

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Tries to fix the issue where these files get auto-fixed over and over: https://github.com/gnosis/cowswap/pull/1616/commits/8246c969f923ee1b0cdd3d1e95ced7cbb4de43bd 

I think is fine to leave the originals. eslint should format (using prettier), my thinking is the prettier part is not needed as a standalone thing. I think that might be the issue.

eslint has already the same config we use in the project.

### CODE REVIEW

**Comment by alfetopito** [comment]
You need to adjust the base in this PR, too many unrelated changes

**Comment by anxolin** [comment]
The linter didn't solve the issue, my theory was proven wrong.
The bot didn't fix this file https://github.com/gnosis/cowswap/pull/1616/commits/0ab78a9727a87bbb467581c10ebc0a699a160b4d

 @alfetopito let's go with your approach

**Comment by anxolin** [comment]
@

**Comment by alfetopito** [comment]
Well, my prettier ignore change has been added to develop already with this PR https://github.com/gnosis/cowswap/pull/1568

It was part of pre-sign, and now it's there.

**Comment by anxolin** [comment]
okok, so then I didn't test my assumption :) if yours work im also good...

**Pull request closed without merging**
