### PR TITLE
change network name: xDai -> Gnosis Chain

### LINKED ISSUE #2021: Rename xDai to Gnosis Chain
Task: Rename xDai to Gnosis Chain.
No need to rename variables, only what's user visible like the network selector chain name

image

### PR DESCRIPTION
**Pull request by alongoni**
# Summary

Fixes #2021 
image

  # To Test

1. <<Step one>> Open the network selector: Now you can see and select "Gnosis Chain"

### CODE REVIEW

**Comment by alfetopito** [comment]
Awesome Agustin, thanks for the quick response.

I'd like to ask to keep the same icon as before, since it hasn't changed (maybe it'll but I don't know if that's the case)

Screenshot from 2021-12-20 16-17-42


https://www.xdaichain.com/

**Review by matextrem — APPROVED** [review]

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @alongoni , great job!

However, some issues: 
1. XDAI is displayed in the Activity modal 
activity modal
2. Tokens in the token list show xDAI 
token list
Seems that this question is related to the same one in Explorer https://github.com/gnosis/gp-ui/pull/918#issuecomment-998545750 , so I'm addressing it to @alfetopito  😊
3. The same is for token names when import custom tokens
import token

**Comment by alfetopito** [comment]
Repeating what I said in the other issue regarding the tokens that contain xDai in their names.
I don't think we should change that yet. Out of the scope of this task.

**Review by elena-zh — APPROVED** [review]
LGTM!

**Review by alfetopito — APPROVED** [review]

**Comment by avsavsavs** [comment]
Hey, additionally to the written name changes, can we also update the corresponding logos to this ones: https://www.xdaichain.com/media/media-kit 

At least the chain one, im guessing the token one is dependent on the token lists being update.

**Comment by elena-zh** [comment]
@avsavsavs , I reported a separate issue for this #2065 as the current task is already merged and closed.

**Pull request merged**
