### PR TITLE
bold numbers in T&C page

### PR DESCRIPTION
**Pull request by rootial**
# Summary
Bold numbers in the T&C page to make it look better as feedback from this [issue](https://github.com/gnosis/cowswap/issues/1173)

# Test
- before
image

- after
image

As we can see the number is bold and looks consistent with other content

# Reviewers
@anxolin @biocom

### CODE REVIEW

**Comment by elena-zh** [comment]
Could you please provide a preview link to test the changes?

**Comment by rootial** [comment]
@elena-zh  i test it locally, what should i do to generate a preview which you can access?

**Comment by rootial** [comment]
hi @biocom , can you please take a look at this PR? And how can i trigger a deploy to generate a preview for it? thanks

**Comment by elena-zh** [comment]
@rootial , I believe @anxolin , @biocom could help with this...

**Comment by alfetopito** [comment]
I believe that due to how github is setup, external contributors won't have access to our full CI infra.
I approved the CI run but I expect it to fail.

Best way to test is setting it up locally in this case.

**Comment by rootial** [comment]
Hi @alfetopito , i have tested locally and please refer the screenshoot above. thanks

**Review by elena-zh — APPROVED** [review]
I reviewed the changes file: Looks good to me.

**Review by alongoni — APPROVED** [review]
Changes LGTM! thanks @rootial!

**Comment by rootial** [comment]
Hi @biocom , can you help review and merge this PR. I can't enable the CI to run from the fork repo and have no write access to commit to the develop branch directly. but i test it locally, should work. thanks~

**Review by anxolin — APPROVED** [review]

**Comment by anxolin** [comment]
Thanks for your contribution @rootial!

**Pull request merged**
