### PR TITLE
Claim invest general error msg

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Waterfalls onto #2250 

Hide/show investment error msg when there are errors
Also updated the msg to be more general.

Screen Shot 2022-01-21 at 15 15 47

Of course feel free to suggest something else

  # To Test

1. Try to claim something paid and make sure to fail the validation

### CODE REVIEW

**Review by nenadV91 — APPROVED** [review]
:ok_hand:

**Comment by biocom** [comment]
Looks good. Wonder if we should summarize all the errors below. But probably overkill in the end 👍🏼

**Review by fairlighteth — APPROVED** [review]

**Review by anxolin — APPROVED** [review]
it works for me!

I think this solution is good enough 💪

**Comment by anxolin** [comment]
> Looks good. Wonder if we should summarize all the errors below. But probably overkill in the end 👍🏼

I had the same thought. But there's also value in keeping the message short. And the other errors are self explanatory

**Comment by elena-zh** [comment]
LGTM!

**Pull request merged**
