### PR TITLE
Re-style FAQ menu.

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Refactors the FAQ menu positioning and layout
- Shows the current active page in the menu
- Remains 'sticky' on scroll for Desktop
- On Mobile/small viewports for now as simple 'expand' logic to show the full menu
- Some consistency/text changes requested by @elena-zh 
- The 'back' button has been removed in favor of the side nav menu. On mobile there's room to improve this by having a sticky menu there as well.

**Desktop**

https://user-images.githubusercontent.com/31534717/160651341-25e75378-936a-4c44-b130-9a6e02f9ee08.mov

**Mobile**

https://user-images.githubusercontent.com/31534717/160651393-b2532fb9-1057-4158-8a0e-cacb59423a9e.mov

# Todos for future PR's
- Detect mobile/small viewports when detecting a resolution change. Right now it only detects it on page load (using the default `isMobile` hook. Currently when you load the page on Desktop then resize to small, it will not perform the onClick behavior  to expand the menu.
- Improve the mobile expanding menu further
- Show subsections in the side menu (left) or in a separate menu on the right.

### CODE REVIEW

**Comment by fairlighteth** [comment]
General comment:
Noticed that many of our routes don't have a fallback from / to no slash. E.g.
`/faq/` => `/faq`

Right now for instance `/claim/` or `/profile/` will simply return a 404. Given we have no server redirects in place, should we simply add those extra routes in the App?

**Comment by elena-zh** [comment]
> General comment: Noticed that many of our routes don't have a fallback from / to no slash. E.g. `/faq/` => `/faq`
> 
> Right now for instance `/claim/` or `/profile/` will simply return a 404. Given we have no server redirects in place, should we simply add those extra routes in the App?

@fairlighteth , we have related issues reported on the board: #1794 and might be #1674

**Comment by elena-zh** [comment]
Hey @fairlighteth , great changes!
Some my notes: 
1. WIN10+tablet and mobile views: impossible to expand the menu
not clickable
2. Seems that the text changes I suggested were not applied: 
text
3. Can we add a 'minus' icon in order to collapse the menu? However, maybe this was not added intentionally
image

4. I think, it would be nice to add an additional margin between these sentences in a mobile view
add margin

Thanks!

**Review by elena-zh — APPROVED** [review]
@fairlighteth , great! 
Maybe some kind of a nitpick, but from my perspective it would be better to change the menu color for the menu, as it looks to dull to me
image

**Comment by fairlighteth** [comment]
@elena-zh Thanks for reviewing. I will keep your comment in mind for a follow up PR!

**Review by nenadV91 — APPROVED** [review]

**Pull request merged**
