### PR TITLE
WIP - Orders panel part 7 (TBD)

### PR DESCRIPTION
**Pull request by biocom**
# Summary

Fixes:
- https://github.com/gnosis/cowswap/issues/1245
- https://github.com/gnosis/cowswap/issues/1238

### CODE REVIEW

**Comment by elena-zh** [comment]
Changes for the linked issues LGTM

**Review by alfetopito — APPROVED** [review]

**Review by anxolin — COMMENTED** [review]
I will do an overall review, and try to list a few things that are missing, just so I make sure they are also in your list (maybe we could have a single issue where we have the checklist?):

SOME KEY NOTES
* Functionally great, i think this feature will improve greatly the UX!
* I love how is easier to see your account in Etherscan or copy the address. More visible
* Colors and labels looks great.

**TODO LIST:**
- [ ] Add limit price
- [ ] Empty list message for the recent history
- [ ] Should the pannel have some annimation so it comes from the side? 
- [ ] `Valid to` is fine, although in my head sounds better `Expiration` or `Expires`, but probably others have other view.
- [ ] The copy functionality could be also done by clicking the address if we have a copy icon next to it. It feels more natural to click on the address to me. Also would leave the second button for "View all history" once that's ready (soonish will be)
- [ ] Ideally, the token is clickable and would open a new window, taking us to Etherscan
- [ ] Make sure we still persist normal transactions and they are placed in the right spot. Or, is it easy to get them from an API too? (no need to put too much effort)
- [ ] Add "View all history", maybe in a button on top, and also, if there's more than 10/20 trades (whatever limit we set on the number of items), we would add it on the bottom of the list.
- [ ] Nit: why is the closing button (X) in the middle, instead of on the right? if it has some margin with the edge and all the top is cliclable should be fine imo
- [ ] Nit: maybe we can improve a bit the cancelation label.

image

- [ ] The unwrap label is wrong. It says "Approved", but it should be "Unwrapped"
image



**TODO after we finish this functionality** (or in parallel, someone could help):
- [ ] Load from the API
- [ ] Handle errors loading orders
- [ ] Remove clear activity. Double check if everyone is ok with this.

**Review by anxolin — APPROVED** [review]
I think i added my comment in the wrong PR, this is why I added the "ist message for the recent his" I see this PR solves what promises. I will approve, the list of thing can be added together with yours in some other place and mark this as approved.

**Comment by biocom** [comment]
Thanks for reviewing @anxolin 

Could you elaborate on 
> Ideally, the token is clickable and would open a new window, taking us to Etherscan

Right now your transaction is clickable, taking you to GP. Do you mean, the individual token should be clickable as well? If that's the case, I think that conflicts with the main purpose of the tx detail, unless we introduce new specific buttons like 'View on GP' etc. 

> Should the pannel have some annimation so it comes from the side?

Yes we could do that. Saving this item as the last of items to address.


> The copy functionality could be also done by clicking the address if we have a copy icon next to it. It feels more natural to click on the address to me. Also would leave the second button for "View all history" once that's ready (soonish will be)

Yes I think a good suggestion. Will try to address this in a separate PR.

> Add "View all history", maybe in a button on top, and also, if there's more than 10/20 trades (whatever limit we set on the number of items), we would add it on the bottom of the list.

Which would bring you to the GP user details tab we plan to introduce? In that case I'd make it something persistent.


> Nit: why is the closing button (X) in the middle, instead of on the right? if it has some margin with the edge and all the top is cliclable should be fine imo

Primarily for alignment purposes, given the content beneath it is centered. Indeed the whole width of the X container is clickable.

> Nit: maybe we can improve a bit the cancelation label.

Sure, please elaborate?

**Comment by biocom** [comment]
Merging, but will keep/remember your comments to be addressed/discussed @anxolin

**Comment by anxolin** [comment]
>> Ideally, the token is clickable and would open a new window, taking us to Etherscan
> Right now your transaction is clickable, taking you to GP. Do you mean, the individual token should be clickable as well? If that's the case, I think that conflicts with the main purpose of the tx detail, unless we introduce new specific buttons like 'View on GP' etc.

It's fine. If the whole row take us to the explorer, that is enough. ignore that comment. 


>> Add "View all history", maybe in a button on top, and also, if there's more than 10/20 trades (whatever limit we set on the number of items), we would add it on the bottom of the list.
> Which would bring you to the GP user details tab we plan to introduce? 

Exactly

> In that case I'd make it something persistent.

didn't get what u mean with persistent


> > Nit: maybe we can improve a bit the cancelation label.
> Sure, please elaborate?

It's kind of fine, it just looks less refined than the rest of the elements. I can't put the finger on it exactly, and note is just a ubernit. it comes to mind doing in a single line (no wrapping), capital letters, and not sure if slightly different background? 
Anyways, ignore this one if u think is good, u know better than me.

**Comment by biocom** [comment]
> In that case I'd make it something persistent.
> didn't get what u mean with persistent

What I meant is, I'd show this 'View all history' or 'View all orders' (link to GP) at all times. Perhaps only when you have at least 1 GP transaction on your wallet. But would be fine with showing it without any conditions as well, so users are already aware of the feature.

> It's kind of fine, it just looks less refined than the rest of the elements. I can't put the finger on it exactly, and note is just a ubernit. it comes to mind doing in a single line (no wrapping), capital letters, and not sure if slightly different background?
Anyways, ignore this one if u think is good, u know better than me.

Sure I see your point. One thing we could do, is replace the 'OPEN' state with `Cancelling...`. And show a specific style for it. I can iterate on it!

**Comment by anxolin** [comment]
> One thing we could do, is replace the 'OPEN' state with Cancelling.... And show a specific style for it. I can iterate on it!

That sounds good to me 👌

**Comment by anxolin** [comment]
> What I meant is, I'd show this 'View all history' or 'View all orders' (link to GP) at all times. Perhaps only when you have at least 1 GP transaction on your wallet. But would be fine with showing it without any conditions as well, so users are already aware of the feature.

Agree

**Comment by elena-zh** [comment]
Just to clarify: currently transaction log is stored for 24 hours https://github.com/gnosis/cowswap/issues/912#issuecomment-881938479
Will it be stored forever in the new side bar?

**Comment by alfetopito** [comment]
> Just to clarify: currently transaction log is stored for 24 hours [#912 (comment)](https://github.com/gnosis/cowswap/issues/912#issuecomment-881938479)
> Will it be stored forever in the new side bar?

Not part of this current iteration Michel is working on, but we intend to fetch the orders from the backend and show the last 10 orders, without a time limit, in whatever browser/device you are connected to.

**Pull request merged**
