### PR TITLE
Add governance card banner.

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

Part of a waterfall PR. Adds the governance styled card banner:
Screen Shot 2022-03-18 at 17 39 56
Screen Shot 2022-03-18 at 17 41 20

### CODE REVIEW

**Comment by fairlighteth** [comment]
Issue to handle: Light mode, on hover of text links, the text is black (cc @elena-zh )

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @fairlighteth , great!

Could we add a 'hovered' effect to the banner as we do on the Claim page? https://watch.screencastify.com/v/fyqv1ml5vsX7EiYQAHb6

Also, I noticed that in this PR tooltip icons on the affiliate form have became changed in the light mode. 


Besides, hovered links are in black in the banner and are hard to read (again, in the light mode), so it would be nice to make them brighter.


Thanks!

**Comment by fairlighteth** [comment]
@elena-zh Thanks for reviewing.
> Could we add a 'hovered' effect to the banner as we do on the Claim page?

In this case we have 2 distinct click actions. The difference with the banner on the claim page is that the whole banner is a 'link'. I would therefore not add this hover effect on the whole governance banner.

> Also, I noticed that in this PR tooltip icons on the affiliate form have became changed in the light mode.

Yes, this todo point was mentioned in the base PR and will be addressed there.

**Comment by anxolin** [comment]
Great! it looks amazing

**Pull request merged**
