### PR TITLE
Total vcow on investment summary

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Show total vCOW amount on investment summary page

Screen Shot 2022-01-20 at 11 24 19

  # To Test

1. On claim page, pick a wallet that has at least 1 investment
2. Proceed to the last step
* Total amount on top should match the sum of all the investments + free claims displayed on the page

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]

**Comment by elena-zh** [comment]
Great changes!

**Comment by biocom** [comment]
Looks good! We could consider still showing the smaller top title, above the amount. Just like on the first page. Something like:
> Total amount to claim

**Review by fairlighteth — APPROVED** [review]

**Comment by biocom** [comment]
@alfetopito Looks good!

**Review by anxolin — COMMENTED** [review]
Love it

**Pull request merged**
