### PR TITLE
Optimise error messages (claim)

### PR DESCRIPTION
**Pull request by biocom**
# Summary

- Re-uses the `ErrorMessage` styled component to improve display of (validation) messages.
- Distinguishes between 'danger' (error) messages and 'info' messages. This way errors are in better contrast with info messages.
- Changed text on some of the validations. Feel free to amend/review.

Screen Shot 2022-01-28 at 18 24 37
Screen Shot 2022-01-28 at 18 24 07
Screen Shot 2022-01-28 at 18 23 55
Screen Shot 2022-01-28 at 18 20 14
Screen Shot 2022-01-28 at 18 20 02
Screen Shot 2022-01-28 at 18 19 07
Screen Shot 2022-01-28 at 18 17 57
Screen Shot 2022-01-28 at 18 17 47

### CODE REVIEW

**Comment by alfetopito** [comment]
I personally find that these colors (as well as the previous orange) do not have a good contrast on dark mode
Screen Shot 2022-01-28 at 10 24 13

Is it just me?

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @biocom , nice!

But as for @alfetopito I also think that it would be nice to make a better contrast for the messages in the dark mode. 
Btw, I personally do not like 'pink' colors 😬. At least they remind me Uniswap colors...

Also, I'd like to propose to make these messages brighter to pay user's attention to them. WDYT?
image

**Comment by biocom** [comment]
Update the color red color for the different color modes. Also double check if the color contrast meets the contrast ratio AA score:
Screen Shot 2022-01-31 at 14 57 23
Screen Shot 2022-01-31 at 14 58 02
Screen Shot 2022-01-31 at 14 57 52

---

Screen Shot 2022-01-31 at 14 57 35
Screen Shot 2022-01-31 at 14 55 51
Screen Shot 2022-01-31 at 14 55 44

**Comment by biocom** [comment]
Pushed an updated to address @elena-zh 's comment on
> Also, I'd like to propose to make these messages brighter to pay user's attention to them. WDYT?

Screen Shot 2022-01-31 at 17 32 47
Screen Shot 2022-01-31 at 17 32 39

**Comment by elena-zh** [comment]
LGTM!

**Pull request merged**
