### PR TITLE
Style tokenlist tabs.

### LINKED ISSUE #361: Fix styles for the Token list toggle
We lost the "toggle", at some point in the past we had highlighted the selected tab here:

### PR DESCRIPTION
**Pull request by biocom**
Fixes #361 

Screen Shot 2021-06-23 at 15 12 31
Screen Shot 2021-06-23 at 15 12 19

A couple of related items captured in issue #796

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
👌

**Review by alfetopito — COMMENTED** [review]
Looks great!

2 tiny issues, which I don't see as big deal, but anyway:

1. Can't tell there's an input in either mode
2. On dark mode, `0 custom tokens` seems a bit faded. Might be hard to read.
screenshot_2021-06-29_12-20-51

Apart from that, you'll probably want to re-create the Mod file after #810 is merged.
Maybe there are new things coming, not sure.

**Review by W3stside — COMMENTED** [review]
SOFT APPROVE. same comment about input

**Comment by W3stside** [comment]
@biocom you may have to cherry-pick / redo this from scratch if it's easier. We should get this in for 0.17
can be in the same PR as the changes left from #794 also for 0.17

**Comment by biocom** [comment]
🍒

**Comment by W3stside** [comment]
@biocom should we close this badboi?

**Comment by biocom** [comment]
Yes sir

**Pull request closed without merging**
