### PR TITLE
Bugfix - Copy to clipboard button not working on Wallet connect popup

### LINKED ISSUE #884: [WalletConnect]: 'Copy to clipboard' link is not working
1. open connection modal
2. select WalletConnect
3. press on the 'Copy to clipboard' link

**AR**: the link is not copied
https://drive.google.com/file/d/1VK93C6Wkoe2AtQ8L_R89WR1JazTsyLvM/view

**ER**: the link is copied

### PR DESCRIPTION
**Pull request by matextrem**
# Summary

Fixes #884 

Overrode a version of `@walletconnect/web3-provider` nested dependency from `@web3-react/walletconnect-connector`

  # To Test

1. Open any page. i.e: `about`
2. Connect your wallet using Wallet connect
    -  When modal is open, click on `Copy to clipboard` button.
    -  Wallet connect data should be copied to clipboard.

### CODE REVIEW

**Comment by henrypalacios** [comment]
@matextrem, Nice :partying_face:, 

I see that the copy button now works,  however it is telling you that:  
```bash
Resolution field "@walletconnect/web3-provider@1.4.2-rc.2" is incompatible with requested version "@walletconnect/web3-provider@^1.5.0"
```

I treated this problem like this with [gnosis-ido-ux](https://github.com/gnosis/ido-ux/pull/650), and then I had a lot of problems with the deep links (not necessarily related to adding this), but maybe you can give a try with this **resolution**:
```json
"@walletconnect/ethereum-provider": "1.6.4"
```
I leave some reference issues that may help: 
- [use @walletconnect/ethereum-provider instead of @walletconnect/web3-provider](https://github.com/Uniswap/uniswap-interface/pull/2175)
- [fix: update walletconnect for deep links and scalability](https://github.com/Uniswap/uniswap-interface/pull/2215)

**Comment by elena-zh** [comment]
changes LGTM!

**Review by alfetopito — APPROVED** [review]
Working fine for me

**Review by henrypalacios — APPROVED** [review]
You got it. :+1:

**Pull request merged**
