### PR TITLE
[0.17] Fix unsupported token error on fee

### LINKED ISSUE #1013: 'Error loading price' error is displayed when select an unsupported token
'Error loading price' error is displayed when select an unsupported token in a From/To field

Failing request:
https://protocol-xdai.gnosis.io/api/v1/fee?sellToken=0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d&buyToken=0xbcfB2B889F7bAa29Dd7A7B447b6C87Aca572F4f4&amount=500000000000000000&kind=sell

It would be nice to show 'Unsupported token' message instead

### PR DESCRIPTION
**Pull request by W3stside**
# Summary

Fixes #1013 
@elena-zh can you put the issue number once you know it? Thanks!

*Fee request can also run into UnsupportedToken error which wasn't being properly handled by our error handling thus always defaulting to network error. Now shows and adds token to unsupported list*

image

  # To Test

1. <<Step one>> Open the page `about`
- [ ] XDAI chain
- [ ] WXDAI SELL <> AAVE
- [ ] Input an amount
- [ ] Should show unsupported token error and NOT Error fetching quote. If the latter, check networks console that it wasn't actually a network/server down issue

### CODE REVIEW

**Comment by elena-zh** [comment]
@W3stside , changes LGTM besides one issue: token address exceeds the unsupported token modal area in a mobile view 
image

Could you please fix it?

Thx

**Review by elena-zh — APPROVED** [review]
LGTM!
One related minor issue for mobile screens #1021

**Comment by W3stside** [comment]
@elena-zh you closed the PR 😅 careful

**Comment by elena-zh** [comment]
@W3stside , sorry about that! =/

**Review by alfetopito — COMMENTED** [review]
:+1:

**Pull request merged**
