### PR TITLE
Adds deterministicHash function to deterministically hash any value using sha256

### LINKED ISSUE #955: [Affiliate] Hash metadata doc
# Summary

Hash metadata doc using SHA-256

While we are re-considering the use of IPFS, we'd like to hash the JSON doc using the same method. See https://docs.ipfs.io/concepts/hashing/#content-identifiers-are-not-file-hashes

The goal of this task is to create a hash fn that takes in a JS object and returns the SHA256 hash for it.

This will likely be a single utils function.

# Requirements

- Hash metadata doc using SHA-256
- "Minify" the JSON (remove unnecessary spaces, line breaks, etc)
- Sort keys alphabetically for deterministic hashing (does JSON.stringify already do that? Unsure)
- Unit tests

# Out of scope

- 

# Additional context

- Wireframes: https://www.figma.com/file/P0AIwKkIUpEZtLukkCUM94/CowSwap_-Affiliate?node-id=48%3A224
- Design doc: https://docs.google.com/document/d/1PsdWn9WPFf2BNeoJNtClyra8jNvWk_bJ-g33TbpUf8s/edit#

### PR DESCRIPTION
**Pull request by ramirotw**
# Summary

Closes #955

Adds a `deterministicHash` function to hash any JS value deterministically using sha256

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Review by W3stside — COMMENTED** [review]
[comment approving] doesn't ethers or some library already in here do this for us?

**Comment by ramirotw** [comment]
> [comment approving] doesn't ethers or some library already in here do this for us?

I couldn't find any that guaranteed what was needed. Glad to see other approaches

**Comment by alfetopito** [comment]
> [comment approving] doesn't ethers or some library already in here do this for us?

Ramiro is using ethersjs to build the byte array `const bytes = utils.toUtf8Bytes(s)` and actually hash the data `utils.sha256(bytes)`.
I assume there's no function to directly take in a JSON obj and extract the hash, thus this one.

**Comment by W3stside** [comment]
then colour me convinced. merge away!

**Review by W3stside — APPROVED** [review]

**Pull request merged**
