### PR TITLE
btn hover state fix

### LINKED ISSUE #1500: 404 page: 'Back home' buttons text color is incorrect in hovered state
'Back home' buttons text color is incorrect in hovered state
Light mode: 

Dark mode: 

**Expected**: 'Back home' button's states should match the 'Swap' button states:
Light mode:

Dark mode:

### PR DESCRIPTION
**Pull request by maria-vslvn**
# Summary

Fixes #1500 

Back btn hover state is incorrect at the 404 page
  # To Test

1. Go to the page `404` by typing wrong route
2. Hover the Back btn

### CODE REVIEW

**Comment by elena-zh** [comment]
@maria-vslvn ,  as far as I understand, 'Back home' button should follow styles of the 'Swap' button. Am I correct, @alfetopito ?
But currently, styles of these buttons are different: 
Hovered state: 
hovered state
Active state: 
clicked state
Focused state:
focused

Also, buttons' styles are different in the light mode. 

Btw, I have created another issue related to buttons' styles: #1677

**Review by elena-zh — APPROVED** [review]
I have created a separate issue for the 'Connect Wallet' button's boarder

**Comment by alfetopito** [comment]
The `connect wallet` button on top has a different style on purpose AFAICT.

As always, @biocom can tells us whether it should be like that or not.

And it's indeed out of the scope of this PR.

I'll just wait on Michel's final input on this one before merging.

**Comment by biocom** [comment]
Yes indeed the button on top should be like that. In general I'd recommend not changing any of the existing button styles outside of the scope of this PR.

**Pull request merged**
