### PR TITLE
Add vCOW banner link.

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Adds a vCOW banner. Previously this was a text link below the primary action button.

https://user-images.githubusercontent.com/31534717/151347832-409e0535-1357-4ffe-b071-d172b4fabcc5.mov

Screen Shot 2022-01-27 at 12 09 33

Screen Shot 2022-01-27 at 12 10 27

## Note
- Please review the text in case we want to modify this. Just put a suggestion in place in this PR.

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
Looks great! 🔥

I think is perfect. Now, there shouldn't be so many questions regarding the investment and vesting, at least people will see the post for sure.

@avsavsavs @annamsgeorge maybe you will like to check this PR one

**Comment by elena-zh** [comment]
Looks great!

But don't we want to add it to these screens? 
image
image

Currently, we have 'Read more' there

**Comment by biocom** [comment]
@elena-zh Yes, I see your point. Question is, how relevant is it to see that banner considering:
- I have no claim account inputted yet.
- I have a claim account without any claims.

From one side, you could say it only adds noise to add the banner there. Curious on your thoughts.

I do think we need to add it here (airdrop only)
Screen Shot 2022-01-27 at 13 21 37

**Comment by biocom** [comment]
@elena-zh Pushed an update to show the banner for the simple airdrop case:
Screen Shot 2022-01-27 at 13 27 14

**Comment by elena-zh** [comment]
@biocom , thanks for adding the banner to the Airdrop screen!

> From one side, you could say it only adds noise to add the banner there. Curious on your thoughts.

Agree. 
The only one 'pros' for adding this banner to 0 screens is that a user might want to read about vCOW and learn more about it. 
Previously we provided this opportunity, now we don't. 
As an option, we could leave 'Read more' link instead of the banner on these screens in order not to add noise.

**Comment by elena-zh** [comment]
@biocom , another nitpick: link arrow is displayed in a separate line in iPhone 12 mini. 
Does this issue worth fixing or we can leave it as it is for now?
image

**Comment by biocom** [comment]
> @biocom , another nitpick: link arrow is displayed in a separate line in iPhone 12 mini. Does this issue worth fixing or we can leave it as it is for now? image

One quick way to fix is to add a few extra words...this banner component is shared so seems to be a more practical solution for now.

**Comment by biocom** [comment]
Merged in the vesting banner PR to consolidate (#2327)

**Review by elena-zh — APPROVED** [review]

**Pull request merged**
