### PR TITLE
Rename gnosisProtocol to cow

### PR DESCRIPTION
**Pull request by W3stside**
Renames all gnosisProtocol files/paths to cow

Personal preference to use shorter `cow` name but could also be `cowProtocol`

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
Is this pressing?
Could you hold this until after unimerge is, well, merged?
Or point this change to that branch instead? 

🥺

**Review by elena-zh — APPROVED** [review]
LGTM

**Comment by W3stside** [comment]
can wait @alfetopito

**Review by anxolin — APPROVED** [review]
Approving, although probably will be easier to just do a new PR after unimerge

**Pull request closed without merging**
