### PR TITLE
Update MEV value (line 89)

### PR DESCRIPTION
**Pull request by avsavsavs**
Changed the value in line 89 from the old one to the current date one.

# Summary
Fixes Issue #1052

*Updating the value to the up to date one*

### CODE REVIEW

**Comment by elena-zh** [comment]
Changes LGTM. 
The only thing is that there was no space between the number and 'M', currently it presents. It would be nice to remove it.
image

**Comment by W3stside** [comment]
@anxolin @elena-zh @alfetopito @biocom develop or release?
can then add the merge when green label once decided on base branch and approved

**Comment by W3stside** [comment]
@avsavsavs always add one of us for review please.

**Review by alfetopito — APPROVED** [review]
I've changed the base to `release/0.17.0` branch and removed the extra space as pointed out by Elena

**Pull request merged**
