### PR TITLE
2382/already claimed

### LINKED ISSUE #2382: Message about available claims appear when a user has already claimed
The app says me that I have available claims in GC (for connected and disconnected scenario), but I have already claimed all options there and get 0 tokens to claim when switch to GC. See the video: https://watch.screencastify.com/v/3pkTurEDNCzjTMNk8ISn

**Expected**: do not show warning message when a user has already claimed in that network and has 0 vCOW tokens to claim.

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #2382 

Once you load the network you have claims on, and all claims are gone, remove the banner on other networks

https://user-images.githubusercontent.com/43217/152618830-7e925ea5-2548-454d-9f43-f5d2d504b82e.mov

  # To Test

1. Load one account that has claims on other networks
2. Go to the other network
3. Claim everything on that network
4. Go to other network
* The banner about the network you claimed everything should no longer be displayed

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alfetopito , great!
But I noticed, that the app freezes in this PR when I change networks. See the video: https://watch.screencastify.com/v/weEOAheFUcUbbtDw89Ue
Could you please take a look at it? 

Also, I noticed that the app still shows available claims banner until I switch to another network and check that the claims have already done there. 
This won't be fixed, correct?

**Comment by alfetopito** [comment]
> Hey @alfetopito , great! But I noticed, that the app freezes in this PR when I change networks. See the video: https://watch.screencastify.com/v/weEOAheFUcUbbtDw89Ue Could you please take a look at it?

That's odd, I'll try to reproduce it.
By any chance did you notice that on other versions or only in this PR?

> Also, I noticed that the app still shows available claims banner until I switch to another network and check that the claims have already done there. This won't be fixed, correct?

Correct. We can only tell if a claim is no longer available if you access the network where you are supposed to have a claim.

**Comment by elena-zh** [comment]
> That's odd, I'll try to reproduce it.
> By any chance did you notice that on other versions or only in this PR?

Hey @alfetopito , I can reproduce the issue in this PR only. 
I tried it in several PRs, on Stage. in #2395 : it is not reproducible there.
image

I test in Win10+Chtome. But I'm able to reproduce it in Firefox and Brave as well.

**Comment by alfetopito** [comment]
@elena-zh looking more closely I found several issues with this PR (😳)

They should all be fixed now and I think the issue you were facing was a mistake causing it to go into an infinite loop.

Hopefully all that is fixed now 🤞

**Review by elena-zh — APPROVED** [review]
LGTM now!

**Review by nenadV91 — APPROVED** [review]

**Pull request merged**
