### PR TITLE
[Release 🐮 ] v1.2.0 

### PR DESCRIPTION
**Pull request by anxolin**
# _Don't squash me broh_

# Release 1.2.0

## Changelog

e4321b80 Merge branch 'master' into release/1.2
1d7d92d7 Fix cypress (#1443)
6bb4fd4e 1.2.0-rc.0
d0176960 Merge pull request #1425 from gnosis/release/1.2.0
d9f26e09 fix: rename weth9 to weth (#2133) (#1424)
3a12c7e0 fix colour/bgColour (#1423)
025890d0 Merge branch 'master' into develop
b07db0eb Show WARNING on high fee relative to swap  (#1295)
8c24d0fe Changing node version on CI scripts from 12 to lts (#1394)
f4215072 [TEMP FIX] Update TS and fix types & lists reducer (#1420)
92cd67b7 Add appDataHash to state (#1189)
b4f72a08 Merge branch 'master' into develop
c8c9a9ae Improve dark mode color styles. (#1401)
c9bd4687 added sentry-webpack plugin for source maps (#1371)
85c4a88d [Bugfix] Move About item from Header to ellipsis menu (#1125)
d9cd27e9 Handle tx cancelation/speedup (#1302)
66b89ffe [USD Price] Add coingecko api and hooks (#1356)
18943ad1 Default cursor for USD est./price impact. (#1361)
fee285bb Merge branch 'master' into develop
52ae4079 Fix status labels for transactions vs orders. (#1374)
b28e578b 1318/tiny amounts displayed as 0 (#1357)
f5172b73 [Cowswap] Implement 404 error page (#1331)
c59cf984 999/2 decimals percentage (#1315)
e299c262 Update question about MEV (#1355)
9bbe443f Merge branch 'release/1.1' into develop
ef83bac8 Merge branch 'hotfix/1.0.3' into develop
461dc4e9 [1283 pt.1] Add Matcha-0x Price source (#1312)

### CODE REVIEW

**Comment by elena-zh** [comment]
seems to be that the last commit (#1455) has not been deployed

**Comment by MareenG** [comment]
> seems to be that the last commit (#1455) has not been deployed

Also #1449 and #1456 were not included

**Comment by W3stside** [comment]
> > seems to be that the last commit (#1455) has not been deployed
> 
> Also #1449 and #1456 were not included

@MareenG yeah the build link is pointing at an old cached version, there was a merge conflict in our package.json file that is now fixed and should update the build momentarily :)

**Comment by anxolin** [comment]
What an awesome version 😎

**Pull request merged**
