### PR TITLE
Responsive claim summary table

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Makes the claim summary table responsive

https://user-images.githubusercontent.com/31534717/150978545-6e4ff670-07dd-419f-8dbc-e6663e83fe1a.mov

## Todo in upcoming PR's
- Highlight each 'card' differently when selected/not selected.
- Make the investment summary table also responsive, using the same approach.

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @biocom , great changes!
Some issues I faced that would be nice to address in a separate PR, I think: 
1. It would be nice to increase distance between 'Change account' and wallet address in iPhone
image

2. When edit the input field in iPhone, the cursor appears in the end of a token name. it is also difficult to set the cursor to a certain place in the field
image

3. It would be nice to add a bit bigger margin between 'Approve token' checkmark and the description
image

4. 'Continue' button on the 'Claim and invest'  screen seems to be in the Clicked state when open the screen
clicked

5. on Android devices, when edit an investment amount, sometimes I start seeing empty 'Available investment bar', however, there is no validation message is displayed. See the video: 

https://user-images.githubusercontent.com/70885163/150987027-663eb2a0-5306-47c5-836e-ec0dfdc1161b.mp4

6. The issue is not exactly related to the current PR, but it would be nice to align an investment amount with 'Balance' label
alignment

**Review by elena-zh — APPROVED** [review]
I created a separate issue #2293 for the notes above.

**Comment by W3stside** [comment]
@biocom can we make the select width 100% (and a button if need be)? I'd also suggest increasing the font size of the card content (not row titles as much as their content)

**Comment by W3stside** [comment]
point this to `release/1.10`

**Review by alfetopito — APPROVED** [review]

**Comment by biocom** [comment]
> @biocom can we make the select width 100% (and a button if need be)? I'd also suggest increasing the font size of the card content (not row titles as much as their content)

Increased the font-size and made the input/checkbox bigger. 

Screen Shot 2022-01-25 at 21 53 52



Not sure about 100% width on the checkbox, given in its unchecked state, it doesn't look like a checkbox but like an input box....
Screen Shot 2022-01-25 at 21 56 21Screen Shot 2022-01-25 at 21 56 10

**Pull request merged**
