### PR TITLE
icons & titles used correctly

### LINKED ISSUE #1511: Profile page: incorrect content of the 'Referrals' section
Related to #1376 , #1506

comparison with the [mock-up](https://www.figma.com/file/bcoZf5RIgVKDItdOaTZq18/GP-Swap?node-id=2647%3A289)

1. Total trades should be named as 'Total referrals'
2. Referrals volume icon should be be 'money with wings'
3. 'Total referrals' icon should be 'shaken hands'

### PR DESCRIPTION
**Pull request by maria-vslvn**
# Summary

Fixes #1511 
it was:
0b455acc-155d-4e46-8cc5-4a62a8aea34b
it is:
Снимок экрана 2021-10-05 в 17 38 44

  # To Test

1. Open Profile page 
2. Compare it to the mockup

Correct title used, Icons used correctly

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Review by ramirotw — APPROVED** [review]
🎉

**Comment by elena-zh** [comment]
Hey @maria-vslvn , could you please provide the PR preview link?

**Comment by ramirotw** [comment]
> Hey @maria-vslvn , could you please provide the PR preview link?

so the issue with the preview app deployment is that the CI task workflow expects the PR to be opened against develop to trigger the deployment.

**Review by alongoni — APPROVED** [review]
Icons looks great!

**Comment by elena-zh** [comment]
LGTM

**Comment by ramirotw** [comment]
So something odd happened with this PR:

1. Since the PR was created using `ramirotw/issue-1406-profile-api` as the base branch instead of `develop`, the preview app deployment wasn't fired.
2. I changed the base branch to develop so the preview app would be deployed and Elena could test Maria's changes
3. Agustin approved the changes and since Leandro set the `Auto-merge` label, the mergify bot merged Maria's changes as well as mine's
4. PR https://github.com/gnosis/cowswap/pull/1506 is no longer needed

@alfetopito thoughts?

**Comment by alfetopito** [comment]
> So something odd happened with this PR:
> 
>     1. Since the PR was created using `ramirotw/issue-1406-profile-api` as the base branch instead of `develop`, the preview app deployment wasn't fired.
> 
>     2. I changed the base branch to develop so the preview app would be deployed and Elena could test Maria's changes
> 
>     3. Agustin approved the changes and since Leandro set the `Auto-merge` label, the mergify bot merged Maria's changes as well as mine's
> 
>     4. PR [[Affiliate] Integrate profile page #1506](https://github.com/gnosis/cowswap/pull/1506) is no longer needed
> 
> 
> @alfetopito thoughts?

Oops...

Accidents happen.

Since the main feature is not fully approved yet even though it's already merged, I suggest the following:

1. Keep the base PR #1506 open until it's approved
2. Rebase it against `develop`
3. Keep updating it as usual
4. If there's anything that's breaking develop, create a new PR to revert/fix it

**Pull request merged**
