### PR TITLE
Hotfix 🔥 - 1.1.1 [removeChild Node crash]

### LINKED ISSUE #1298: Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
**Steps**:
1. Open the app 
2. Press on the built-in browser's translate option 
3. Swap tokens

**AR**: the app is crashed
image

## URL
  
https://cowswap.exchange/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": ""
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "OUTPUT",
  "typedValue": "10",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ks (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2497570)
    at Pu (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2509382)
    at t.unstable_runWithPriority (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2529999)
    at zi (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452357)
    at Mu (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2507340)
    at mu (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2503426)
    at https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452580
    at t.unstable_runWithPriority (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2529999)
    at zi (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452357)
    at Gi (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452525)
    at Ji (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452460)
    at je (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2523809)
    at Qt (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2431084)
    at HTMLDivElement.r (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:4212159)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 8.1.0; VIA_A3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.159",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.159"
  },
  "os": {
    "name": "Android",
    "version": "8.1.0"
  },
  "device": {
    "model": "VIA_A3",
    "type": "mobile"
  },
  "cpu": {}
}
```

### LINKED ISSUE #1304: Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
## URL
  
https://cowswap.exchange/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
  },
  "OUTPUT": {
    "currencyId": "0xdAC17F958D2ee523a2206206994597C13D831ec7"
  },
  "independentField": "INPUT",
  "typedValue": "100",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLSpanElement.removeChild (<anonymous>)
    at ks (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2497570)
    at Pu (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2509382)
    at t.unstable_runWithPriority (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2529999)
    at zi (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452357)
    at Mu (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2507340)
    at mu (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2503426)
    at https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452580
    at t.unstable_runWithPriority (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2529999)
    at zi (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452357)
    at Gi (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452525)
    at Ji (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452460)
    at je (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2523809)
    at Qt (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2431084)
    at HTMLElement.r (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:4212159)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 8.1.0; VIA_A3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.159",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.159"
  },
  "os": {
    "name": "Android",
    "version": "8.1.0"
  },
  "device": {
    "model": "VIA_A3",
    "type": "mobile"
  },
  "cpu": {}
}
```

### PR DESCRIPTION
**Pull request by W3stside**
Hotfix 1.1.1

Fixes #1298 
Fixes #1304

### CODE REVIEW

**Review by fairlighteth — APPROVED** [review]
Tested on Chrome with translations on, and it worked.

**Comment by anxolin** [comment]
All good 🔥

**Comment by elena-zh** [comment]
LGTM!
The app is not crashed, however, balances are not updated in the From/To fields when the app is translated. 
I have created #1387 issue for this case

**Comment by MareenG** [comment]
Not sure if this is related but I experienced the following when using the Google translate add on for Firefox
Bildschirmfoto 2021-09-03 um 12 09 18
Bildschirmfoto 2021-09-03 um 12 10 07

Also in translation mode the balances are stuck
Bildschirmfoto 2021-09-03 um 12 17 04
 
and the point and commas are mixed 
Bildschirmfoto 2021-09-03 um 12 03 31
but this is not important for the hotfix

**Pull request merged**
