### PR TITLE
Fix manage tokens darkmode styles.

### PR DESCRIPTION
**Pull request by biocom**
# Summary

- Addresses https://github.com/gnosis/cowswap/issues/1017
- Input field now has borders
- Consistent trash/external icon colors + hover effect

https://user-images.githubusercontent.com/31534717/127858342-375c0325-40be-495a-8827-8c14710990b3.mov

https://user-images.githubusercontent.com/31534717/127858362-9d2ce41c-6880-433c-91a0-c1325f3ee986.mov

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
HI @biocom , changes LGTM!

Several minor issues that are not related exactly to this pr, but might be fixed here: 
1. Token description is shifted in a mobile view
shifted
2. 'Custom token**s**' is displayed when 1 token is added. it would be nice to show 'custom token' instead. Or rewrite it as 'Custom tokens: < number >'
1s
3. exclamation mark icon is in black in the dark mode on the 'Import token' modal
image

Let me know please if I need to create separate tasks for these issues..

**Comment by elena-zh** [comment]
Actually, I can't understand why, but the list of tokens has stopped to be displayed in this PR, even if I have several lists switched on.. =(
image

**Comment by biocom** [comment]
For some reason, I noticed too and wanted to check if it was only on my machine. But seems to happen there as well. Will have to check...

**Comment by biocom** [comment]
Fixed this issue now.

**Comment by elena-zh** [comment]
Token names are again in black in the dark mode: 
image

Icon colors are different in the dark and in the light modes
image
image

Token list is not cropped in a mobile view
image

**Pull request merged**
