### PR TITLE
Update vcow blog links based on chain id

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Claim blog links should point to correct articles now, as a reference see this msg https://gnosisinc.slack.com/archives/C025G521XQD/p1644256674411799

These links should lead to vCowPost https://cow-protocol.medium.com/7689c4391373
Screenshot from 2022-02-09 11-30-01
Screenshot from 2022-02-09 11-30-34
Screenshot from 2022-02-09 11-32-21

This link should lead to step by step guide and it should be different based on if the selected chain is Ethereum or Gnosis Chain
Screenshot from 2022-02-09 11-30-49

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @nenadV91 , could you please describe a bit better what link should be added here: 
image

and here: 
image

Also, I can't test navigation for this link in the Mainnet and in GC due to claim investment options for these networks has expired
image

Also, could you please clarify whether I have missed other links that I need to retest besides the mentioned above. 
Thanks!

**Review by alfetopito — APPROVED** [review]

**Comment by biocom** [comment]
Looks good. My only comment is that we call the hook `useCowLinks`. The hook seems specifically tailored to blog urls (looking at `const COW_LINKS_ROOT = 'https://cow-protocol.medium.com'`). It's very much a nitpick, but if for some reason we want to re-use this hook in the future (post claim..), and use it for **other** COW related links (like cow.fi or social media) than it wouldn't suffice anymore.

**Comment by nenadV91** [comment]
@elena-zh I've added pointers with pictures in the PR description
@biocom Michel I've updated that hook and const names, if you had something else in mind let me know.

**Review by elena-zh — APPROVED** [review]
@nenadV91 , LGTM!
I was not able to retest navigation for the Mainnet and GC, but I will keep my eye on it when new deployment data with investment options for these networks will be available to me.

**Pull request merged**
