### PR TITLE
[RELEASE 🪄 ] v1.11.0-RC.0

### PR DESCRIPTION
**Pull request by biocom**
# Summary

f4e511fef [2506] Sync BE errors with FE (#2507)
ffbbda986 Use previously supported wallets (#2166)
670ecf383 Revert "Swap page layout (#2488)"
588ccf2fb Add fast price fetching (#2477)
90e6843ee Reduce dependencies (#2480)
795f7fcc5 Fix for claim cancel popup icon (#2501)
67d6294c7 Swap page layout (#2488)
6be36cabd Fix for already claimed button on claim successful screen (#2478)
af2882131 2473/cancel claim issue (#2485)
55ffce351 Fix 404 for OPYN_LIST url (their file name changed) (#2481)
32c4765aa Bump url-parse from 1.5.3 to 1.5.7 (#2476)
a8157ce3f 2150 Terms and Conditions: gnosis forum link (#2483)
6dc3d57fb Scrollbar styles (#2421)
e4364cb90 Fix avilable claims issue on rinkeby (#2420)
7319d6c45 Enhance messages for Affiliate program (#2414)
e28bfd3c2 1867 - Add network if nonexistent (#2424)
918973197 2382/already claimed (#2394)
451206fbb Removed Ethereum word from popup text msg (#2412)
a57279f22 Show banner if the user has claimed already (#2393)
1e1b4090e Menu: view all orders position (#2399)
ad5e98c07 Fix readme path and add users (#2400)
b551f2b57 Merge branch 'hotfix/1.10.1' into develop
af1a7c696 Updated gas estimation for gchain (#2391)
6763fc260 Bump simple-get from 2.8.1 to 2.8.2 (#2392)
ee0101a0b Improve responsiveness of header elements. (#2376)
653d9b60b Add alternative claim success sound. (#2384)
94245c5c7 Fix token display in dark/light mode for transactions. (#2386)
c939d7853 Add CLA (#2390)
d1119ca7f Fix e2e (#2379)
e7feb5dde Moved claim state updater to claim page (#2380)
22fc2d1ac Update confirmation text based on chainId (#2373)
505a3b4c8 Remove some claim functions that are not being used (#2372)
fcb05fe70 Fix claim input error message position (#2368)
913a30a59 remove unused audio. (#2348)

### CODE REVIEW

**Comment by elena-zh** [comment]
I have retested newly added wallets and have no encountered new issues besides these low priority  known ones: 
 - #2514 
 - #2515 
 - #2516 
 - #2517

**Review by anxolin — APPROVED** [review]
I would merge this to master, it's best to test it there the RCs. 

I would think, nothing here is bad that it goes to Barn.

Also,  @elena-zh some 2 imp things that change here would be good to test:
- affiliate: we changed the pinata integration, we just need to make sure is not broken. Also theres the change of removing annoying messages
- faster price response: now we have the 2 price queries (fast and slow). The fast one gives a quick price to the user, the slow one, updates the price later if some better price was found

**Comment by anxolin** [comment]
@biocom Question about this release, if we have the price, as it seems the case, shouldn't we do at least the shimmer effect? 

Maybe the idea of showing all the liquidity providers doesn't need to be here, but probably good to try to round a bit the feature, right?

**Comment by elena-zh** [comment]
@anxolin , seems that 'shimmer effect' is still under implementation here #2510

**Comment by elena-zh** [comment]
> I would merge this to master, it's best to test it there the RCs.
> 
> I would think, nothing here is bad that it goes to Barn.
> 
> Also, @elena-zh some 2 imp things that change here would be good to test:
> 
> * affiliate: we changed the pinata integration, we just need to make sure is not broken. Also theres the change of removing annoying messages
> * faster price response: now we have the 2 price queries (fast and slow). The fast one gives a quick price to the user, the slow one, updates the price later if some better price was found

@anxolin , sure. I will retest it in Staging as well. 
Yesterday I retested these changes in the PR and did not notice any strange behavior.

**Comment by W3stside** [comment]
i would consider adding #2518 as it will add, to prod, better sentry reporting (marginally better, but still)

**Pull request merged**
