### PR TITLE
[Release] 0.17.0-rc.2

### PR DESCRIPTION
**Pull request by W3stside**
# Release 0.17.0-rc.2
Next in the chain of release candidates. Last rc: 

## 👷‍♀️ Changelog (since last rc)
36c178e5 Shadow/slider. (#1082)
da42863f Fix / handle stale V2 order data type in V3 (#1084)
c9d20c69 [1053] Re-enable common bases (#1058)
c6e0d12d [1057] Fix mobile swap confirmation styling (#1063)
5600295 Update MEV value (#1067)
ec001a0 Reduce tooltip 🔥 🔥 HELL🔥 🔥 (#1071)

### Last RC:
VISUALS: lots of visual changes, please make sure colours are ok in both light and dark mode, and please check Dark mode misc #681 for issues already catalogued
NUMBERS/AMOUNTS: the usual there.
COW GAME: that it works well in all formats: desktop, mobile (landscape, portrait), tablet
ORDER CANCELLATION: that it works in V3 context (same testing procedure as last release)
USD price estimations: please make sure:
a. USDC USD price is always 1:1 e.g 500 USDC should show 500$
b. the prices are not crazy divergent from other swaps (uni, sushi etc) - we pull prices differently than other swaps so some discrepancy is expected
XDAI - works as normal:
a. token balances load (can open the token picker for easy checking)
b. can trade normally, no errors happening
ROPSTEN/KOVAN/BLAH BLAH networks that we don't support should show: Wrong Network in the usual network place. No errors

The USDC <> TOKEN amount threshold was lowered from 100k to 100. Check that USD estimations for tokens are more or less sensical and in-line with other dexes.
No more USDC/UNI gasless approval requests for off-chain signing. Should be signing as normal (on-chain)
No / less style issues especially in dark/light mode
Mobile responsive-ness in swap page changes: mobile view is easier to use // better at displaying data (e.g large numbers).

### CODE REVIEW

**Comment by MareenG** [comment]
I still experience some issues with the mobile/small desktop swap confirmation styling 
Bildschirmfoto 2021-07-28 um 10 05 22

**Comment by MareenG** [comment]
Not displayed on mobile
Bildschirmfoto 2021-07-28 um 10 18 47

**Comment by MareenG** [comment]
As we changed the value to the most recent one we should also update the month
Bildschirmfoto 2021-07-28 um 10 25 50

**Comment by elena-zh** [comment]
Just a note: 'Slippage tolerance' on the tooltip has its tooltip icon. 
image

I believe, it will be fixed when #1070 pr is merged here.

**Comment by elena-zh** [comment]
> I still experience some issues with the mobile/small desktop swap confirmation styling.
> This is for the reduced desktop size.
> Bildschirmfoto 2021-07-28 um 10 05 22
> Might be good to not cover the wallet info and menu bar.
> Or the modal should cover the whole screen as on a mobile device

In addition to @MareenG notes, connection modal looks a bit different on reduced screen/certain tablet devices:
image

**Comment by biocom** [comment]
> Might be good to not cover the wallet info and menu bar.
Or the modal should cover the whole screen as on a mobile device

The latter would be good (just to deal with viewport sizes and not devices). Will address.

**Pull request merged**
