### PR TITLE
Updated abis for vCow

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

This PR is part of the previous #2552 PR now separated into this PR and another one for hooks, for the sake of easier review.
- adds `swappableBalanceOf` and `balanceOf` methods on the vCow abi
- separates scripts to build custom Cowswap and Uniswap abis
- adds script to append Uniswap export line to the end of generated `types/index.ts` file

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]
👍

**Review by W3stside — APPROVED** [review]
nice, much easier to read!

**Comment by nenadV91** [comment]
@W3stside Merged :+1:

**Review by anxolin — COMMENTED** [review]
Happy to see you broke it down and move this to another PR.

**Pull request merged**
